forcedotcom/dataloader

src/main/java/com/salesforce/dataloader/dao/csv/CSVFileReader.java
Use CSVReader update to separate fields on commas or tabs.
=> Tabs and commas separate fields, fix regression.

pom.xml
Fix an issue with a missing constructor.
=> Update version of WSC to 33.0.3.

pom.xml, src/main/java/com/salesforce/dataloader/process/ProcessConfig.java
see
http://stackoverflow.com/questions/18744663/how-to-inject-environmental-variables-inside-spring-xml-configuration
=> support ${} syntax. it's provide to access environment.

pom.xml, src/main/java/com/salesforce/dataloader/process/ProcessConfig.java
Reverts forcedotcom/dataloader#63
=> Revert "undo pull request #40"

src/main/java/com/salesforce/dataloader/dao/EncryptedDataSource.java
Ask and you shall receive... eventually.
=> Issue64 - Renamed class and included some inline doc on how to use it.

pom.xml
Hi, 
This pull request is to add spring expression language support for a more easy parameter configuration in files like process-conf.xml and database-conf.xml.
Also added Shade support so Spring dependencies in uber jar don't overlap and append nicely.
=> added spring-expression as depdendency, added maven shade support.

make-pretty-dmg.sh, pom.xml
starting with the hammer. tests right now are connectivity free.
Next step: getting basic and performant connectivity tests back in.
=> housecleaning - mac installer, maven dependencies/warning and trying to reign tests in

pom.xml, setup.nsi, src/main/java/com/salesforce/dataloader/process/FindJavaRunner.java, src/main/nsis/bin/encrypt.bat, src/main/nsis/bin/process.bat
we decoupled java but the paths in the batches were still expecting java to be included. Updated.
=> encrypt and process batches needed updated paths for java

pom.xml, setup.nsi, windows-dependencies/sign.bat
signed version of data loader installer and binaries for windows.
=> added windows signing

src/main/java/com/salesforce/dataloader/action/AbstractAction.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java
Revised bulk load to not catastrophically fail if batch contains errors. Also changed abstract action exit code to make sure it does it's best to report success or failures
=> Updated Bulk API error handling

pom.xml, src/main/java/com/salesforce/dataloader/client/DefaultSimplePost.java, src/main/java/com/salesforce/dataloader/client/HttpClientTransport.java
Upgrade Apache httpClient lib from 4.2.1 to 4.5.2 and update depreciated API calls with connection cleanups.
W-3238933
=> Connection clean up and upgrade httpClient

README.md, src/main/java/com/salesforce/dataloader/client/DefaultSimplePost.java, src/main/java/com/salesforce/dataloader/client/HttpClientTransport.java, src/test/java/com/salesforce/dataloader/client/HttpClientTransportTest.java
Improve http client from potential client leak and adding verification test for Server name indicator in SSL.
=> Improve httpclient with SNI support

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileReader.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/resources/labels.properties, src/test/java/com/salesforce/dataloader/dao/CsvTest.java, src/test/resources/testfiles/conf/config.properties, src/test/resources/testfiles/data/csvSeparator.csv
1. We will support default comma and Tab
2. Give user to select/deselect comma, Tab and other character.
3. Test added
=> Support more control on csv separator characters

README.md, pom.xml
Upgrade the data loader to V38 with the latest V38.*  WSC and partner API.
=> Upgrade to V38

README.md, pom.xml
=> Upgrade to V40

src/main/java/com/salesforce/dataloader/security/EncryptionAesUtil.java, src/main/java/com/salesforce/dataloader/security/EncryptionUtil.java
=> Clean up OS lookup code and few others

pom.xml
Bump up the version and use latest wsc and partner API.
=> Upgrade to 43.0

src/main/java/com/salesforce/dataloader/controller/Controller.java
Adding null check to prevent process.bat throw null exception.
=> Adding null check for command line scenario

README.md, release/mac/dataloader.command, release/mac/install.command, release/win/bin/encrypt.bat, release/win/bin/process.bat, release/win/dataloader.bat, release/win/install.bat
update data loader version in install files
=> update data loader version in install files

pom.xml, src/main/java/com/salesforce/dataloader/config/Config.java
- speed up jar building by skipping dmg creation.
- sign jar using mvn target and jarsigner plug-in.
- fix mvn warning about not specifying the version for maven-compiler-plugin.
- include Windows-specific SWT DLLs in the jar if Windows build target is specified.
=> pom.xml updates

pom.xml, release/mac/dataloader.command, release/mac/install.command, release/win/bin/encrypt.bat, release/win/bin/process.bat, release/win/dataloader.bat, release/win/install.bat
Use existing variable, "version", and introduce a new variable, "short.version", in pom.xml. Use these variables to set values in mac and windows-specific files after copying them to target directory.
=> templatize version information and specify the values in pom.xml

release/win/dataloader.bat
It's far from obvious that ZULU_JAVA_HOME needs to be set. 
I've added a suggested update to dataloader.bat instructions.
=> Suggested update since it's not obvious how to install on windows.

pom.xml, release/win/samples/conf/database-conf.xml, release/win/samples/conf/log-conf.xml, release/win/samples/conf/process-conf.xml, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/main/java/com/salesforce/dataloader/process/ProcessScheduler.java, src/main/resources/com/salesforce/dataloader/version.properties
Fixes include:
- New syntax for log-conf.xml, process-conf.xml, and database-conf.xml in samples folder necessiated by Spring framework and log4j upgrades.
- Fixes in ProcessRunner and ProcessScheduler necessiated by log4j framework upgrade - Controller.initlog() needs to be invoked before instantiating a logger through LogManager.getLogger() call.
- Fixes in Controller.java and version.properties to decouple data loader versioning from the API version used for partner API.
=> Fixes due to the upgraded Spring framework and log4j

src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java
=> reduce the log level for spammy 'no value for column' message

src/main/java/com/salesforce/dataloader/action/visitor/BulkApiVisitorUtil.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkQueryVisitor.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/controller/Controller.java
Support for pilot properties and close the job after all batches are processed.
=> Support for pilot properties and close the job after all batches are processed.

src/main/java/com/salesforce/dataloader/action/visitor/BulkApiVisitorUtil.java
Retry the bulk job status check if it fails instead of failing the entire job to avoid job failure due to intermittent network connectivity issues.
=> retry bulk job status check if it fails

src/main/java/com/salesforce/dataloader/ui/DataSelectionPage.java, src/main/java/com/salesforce/dataloader/ui/entitySelection/EntityFilter.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionDataSelectionPage.java
add ability to search by entity name per issue #261
=> add ability to search by entity name per issue #261

pom.xml, src/main/java/com/salesforce/dataloader/ui/DataSelectionPage.java, src/main/java/com/salesforce/dataloader/ui/EntitySelectionListViewerUtil.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionDataSelectionPage.java
Refactor the code to display Salesforce Objects and simplify license check filter in POM.
=> refactor code, simplify license check in POM.

dlbuilder.sh, pom.xml, src/main/java/com/salesforce/dataloader/ui/AuthenticationRunner.java, src/main/java/com/salesforce/dataloader/ui/Grid12.java
- Change pom.xml for v52 upgrade
- Improve logged message on console if OAuth login dialog is closed without logging in.
- Use enum for gridLayout default height instead of integer literal for better code maintainability.
=> upgrade to v52

release/win/install.bat
Simpler fix for the issue - Data Loader for Windows - can't install data loader as admin
=> Data Loader for Windows - can't install data loader as admin

dlbuilder.sh, pom.xml
Sign jar and zip using jarsigner plugin. Build Mac ARM-specific zip.
=> Sign jar and zip using jarsigner plugin. Build Mac ARM-specific zip.

src/main/java/com/salesforce/dataloader/dao/csv/CSVFileReader.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileWriter.java
debugging messages to troubleshoot #274
=> logging to troubleshoot #274

dlbuilder.sh
add -u option to produce unsigned jar and zip files.
=> add -u option to produce unsigned artifacts

pom.xml
Resolves #283
Upgrade the eclipse repository dependency to use HTTPS.
=> Upgrade eclipse repository reference to https

release/mac/install.command, release/win/install.bat, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java
- Upfront checks in the batch mode to make sure that the required parameters are specified either in the process DynaBean or in the config.properties file.
- Minor improvements in the installation scripts to not deploy .ico, META-INF, and other unused files in the installation folder.
=> upfront checks in the batch mode. Minor improvements to installation scripts.

src/main/java/com/salesforce/dataloader/action/visitor/BulkV2Connection.java
minor tweaks to the sample client code for BulkV2Connection
=> minor tweaks to the sample client code for BulkV2Connection

pom.xml
see java compiler errors when compiling through maven
=> see java compiler errors when compiling through maven

dlbuilder.sh, pom.xml
- Simplify activation of OS-specific profiles
- Reduce maven warnings
=> pom cleanup and reduction in Warnings

pom.xml
pom.xml cleanup to fix WARNING messages.
=> pom.xml cleanup to fix WARNING messages

dlbuilder.sh
=> improvements to dlbuilder.sh

.gitignore, pom.xml, swtinstall.py
- removal of unused dependencies
- spring version upgrade
- swtinstall.py updates SWT version to the latest installed SWT in pom.xml
=> pom cleanup and automate SWT version update in pom.xml

pom.xml
update pom.xml with the latest versions for surefire plugin
=> update pom.xml with the latest versions for surefire plugin

dlbuilder.sh, pom.xml
change in dlbuilder.sh and pom.xml to support PKCS11
=> change in dlbuilder.sh and pom.xml to support PKCS11

runtests.sh
- option to run a specific test
- option to debug
- option to specify an older WSC version for testing purpose
- parameters for test org URL
=> script to facilitate test runs

dlbuilder.sh
minor fix to build the uber jar
=> minor fix to build the uber jar

pom.xml, runtests.sh, updatePOMDependencies.py
- pom.xml contains URL of the maven repo for plugins
- python script handles plugin updates
=> specify maven plugin repos for updating to the latest version

runtests.sh
parameterize the OS platform to run the tests on
=> parameterize the OS platform to run the tests on

src/main/java/com/salesforce/dataloader/ui/OAuthLoginFromBrowserFlow.java
part of the fix for issue #328 - handle MFA through login from browser - Missed checkin of a newly created java class.
=> Fix for issue #328 - handle MFA through login from browser

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVColumnVisitor.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileWriter.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/resources/labels.properties
Support the ability to escape  excel formula in extracted results by inserting a single quote character in the extraction result written to the csv file.
=> support the ability to escape excel formula in extract results

pom.xml
reduce zip size by including SWT files for the relevant OS platform
=> reduce zip size by including SWT files for the relevant OS platform

pom.xml
remove unused maven-shade-plugin and minor cleanup
=> remove unused maven-shade-plugin and minor cleanup

src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/java/com/salesforce/dataloader/process/SWTLoader.java
minor tweak to set SWT Directory correctly in development
=> minor tweak to set SWT Directory correctly in development

dlbuilder.sh, pom.xml
- remove unused flags to sign jar files in pom.xml.
- simplify dlbuilder.sh to use the same dataloader uber jar in creating platform-specific zip files.
=> cleanup of pom.xml and dlbuilder.sh script

extractSWTJar.xml, pom.xml, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
- iterate over local SWT repos to build package
- make java code to look for SWT jar more robust
=> iterate over local SWT repos to build package

pom.xml
replace tabs with space chars for better indentation.
=> replace tabs with space chars for better indentation.

runtests.sh, updateSWT.py
minor improvements to utility scripts for downloading the latest SWT packages and run tests
=> minor improvements to utility scripts for downloading the latest SWT packages and run tests

pom.xml, runtests.sh
version upgrade of dependencies and fix the script to run tests
=> version upgrade of dependencies and fix the script to run tests

pom.xml, runtests.sh
major version upgrade of H2 DB, used for testing purpose
=> major version upgrade of H2 DB, used for testing purpose

pom.xml
Update log4j-core, log4j-api, and jface versions
=> Update log4j-core, log4j-api, and jface versions

src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
Fix error in the batch mode as reported in issue #365 by loading SWT jar even when in the batch mode.
=> Fix error in the batch mode as reported in issue #365

pom.xml
=> Upgrade log4j to 2.16

release/linux/dataloader.sh, release/mac/dataloader.app/Contents/MacOS/dataloader, release/win/bin/process.bat, release/win/dataloader.bat
Enable setting of DATALOADER_JAVA_HOME environment variable to enable use of a JRE other than the system default.
=> Fix for issue #372

dlbuilder.sh, pom.xml, src/main/java/org/apache/logging/log4j/core/lookup/JndiLookup.java
fix for issue #377 and upgrade to log4j 2.17.0
=> fix for issue #377 and upgrade to log4j 2.17.0

src/main/java/com/salesforce/dataloader/process/ProcessRunner.java
Fix issue #385 by checking either password is set or OAuth access token is set.
=> fix for issue #385

pom.xml
=> patch update of h2

src/main/java/com/salesforce/dataloader/ui/OAuthFlow.java
make OAuth login dialog resizable
=> make OAuth login dialog resizable

src/main/java/com/salesforce/dataloader/config/Config.java
Do not save decrypted properties.
=> part of fix for 393

src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/main/resources/messages.properties, src/test/java/com/salesforce/dataloader/process/BulkCsvProcessTest.java, src/test/java/com/salesforce/dataloader/process/CsvProcessAttachmentTest.java, src/test/java/com/salesforce/dataloader/process/DatabaseProcessTest.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
Tests now call ProcessRunner.runBatchMode() instead of calling getInstance(), followed by run().
=> Minor cleanup of ProcessRunner and related tests

pom.xml
Spring '22 release changes - Upgrade to WSC 54.0.0.
=> Spring '22 release changes - Upgrade to WSC 54.0.0

pom.xml
=> h2 version upgrade

release/win/dataloader.bat, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
Fix issue #410 by skip the setting of org.eclipse.swt.browser.IEVersion if -skipieversion is specified as a command line argument.
=> fix for issue #410

src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
avoid any possibility of NPE when debugging provided command line arguments .
=> extra check when debugging provided command line arguments

pom.xml
Use crlf for line endings in Windows batch file and upgrade H2
=> Use crlf for line endings in Windows batch file and upgrade H2

pom.xml, src/main/java/com/salesforce/dataloader/action/visitor/BulkApiVisitorUtil.java, src/test/java/com/salesforce/dataloader/dao/database/DatabaseTestUtil.java
Dependency updates
- H2
- remove dependency on WSC as it is not used. Only partner API is used.
Bug fix
- fix a bug introduced as a side-effect of PR #449
=> dependency updates and a bug fix

pom.xml
incrementing sub-minor version of data loader to 54.0.2
=> incrementing sub-minor version of data loader to 54.0.2

pom.xml
minor version update of spring-context and spring-jdbc
=> minor version update of spring-context and spring-jdbc

dlbuilder.sh, pom.xml
update for the Summer '22 release (Data Loader v55.0.0)
=> update for the Summer '22 release (Data Loader v55.0.0)

src/main/java/com/salesforce/dataloader/exception/OAuthBrowserLoginRunnerException.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/main/java/com/salesforce/dataloader/ui/OAuthFlow.java, src/main/java/com/salesforce/dataloader/ui/OAuthLoginFromBrowserFlow.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserLoginRunner.java
Refactor OAuth browser login flow so that it is available in both interactive (UI) and batch (CLI) modes.
=> Refactor OAuth browser login flow

pom.xml
update sub-minor version of data loader
=> update sub-minor version of data loader

src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/ui/AuthenticationRunner.java, src/main/java/com/salesforce/dataloader/ui/LoaderWindow.java, src/main/java/com/salesforce/dataloader/ui/uiActions/LogoutUIAction.java
Fix for the issue https://ideas.salesforce.com/s/idea/a0B8W00000GdpL7UAJ/data-loader-information to display org's URL after the user logs in.
=> display org URL after user logs in

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java
Fix for the issue reported at https://ideas.salesforce.com/s/idea/a0B8W00000GdiLfUAJ/fix-settings-window-on-data-loader-18
=> Fix "scroll to the bottom" of Settings dialog

src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionSOQLPage.java
set initial width of field selection table in edit SoQL step.
=> set initial width of field selection table in edit SoQL step

src/main/java/com/salesforce/dataloader/ui/EntitySelectionListViewerUtil.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionDataSelectionPage.java
Fix issue in displaying extraction target file control in Step 2: Select Data Objects during Extraction (Export) operation.
=> Fix issue in displaying extraction target file control

src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionSOQLPage.java
revert to using Combo (from CCombo) for field selection dropdown.
=> revert to using combo for field selection dropdown

src/main/java/com/salesforce/dataloader/ui/EntitySelectionListViewerUtil.java
fix to show the search box during step 2 (select data object) of an operation.
=> fix to show the search box for the sobjects  list

src/main/java/com/salesforce/dataloader/ui/EntitySelectionListViewerUtil.java, src/main/resources/labels.properties
tooltip for "Show all Salesforce objects" checkbox to address the issue reported at https://ideas.salesforce.com/s/idea/a0B8W00000Gdi9lUAB/data-loader-enhancements (item 4).
=> tooltip for "Show all Salesforce objects" checkbox

src/main/java/com/salesforce/dataloader/ui/Grid12.java, src/main/java/com/salesforce/dataloader/ui/OAuthLoginDefaultControl.java, src/main/java/com/salesforce/dataloader/ui/UsernamePasswordLoginStandardControl.java
handle "Enter" key press in password field to process login as requested in https://ideas.salesforce.com/s/idea/a0B8W00000Gdi9lUAB/data-loader-enhancements (item 1).
=> handle "Enter" key press in password field to process login

src/main/java/com/salesforce/dataloader/config/Config.java
make login from browser for OAuth the default.
=> make login from browser for OAuth the default

src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/ui/BaseWizard.java, src/main/java/com/salesforce/dataloader/ui/DataSelectionDialog.java, src/main/java/com/salesforce/dataloader/ui/DataSelectionPage.java, src/main/java/com/salesforce/dataloader/ui/ExternalIdPage.java, src/main/java/com/salesforce/dataloader/ui/FinishPage.java, src/main/java/com/salesforce/dataloader/ui/ForeignKeyExternalIdPage.java, src/main/java/com/salesforce/dataloader/ui/LoadPage.java, src/main/java/com/salesforce/dataloader/ui/LoaderWizardDialog.java, src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/java/com/salesforce/dataloader/ui/MappingPage.java, src/main/java/com/salesforce/dataloader/ui/OperationPage.java, src/main/java/com/salesforce/dataloader/ui/SettingsPage.java, src/main/java/com/salesforce/dataloader/ui/UIUtils.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionDataSelectionPage.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionFinishPage.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionPage.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionSOQLPage.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionSettingsPage.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionWizard.java, src/main/resources/labels.properties
Refactor Wizard and Wizard Page code for maintenance.
- Added a common superclass OperationPage that sets the Wizard page description using the concrete subclass name.
- Using classname as the name in the constructor of a Wizard page instead of fetching it from label.properties.
- Made ExtractionFinishPage a subclass of FinishPage to refactor more code.
- Added getAPIInfo() to Controller so that the code can be used in the UI as well as for logging purposes.
- Added method setPageComplete() in each concrete subclass of OperationPage class so that each page can determine when it is complete and call WizardPage's setPageComplete() method to enable/disable Next and Finish buttons.
=> code refactoring and related cleanup

src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionSOQLPage.java, src/main/java/com/salesforce/dataloader/ui/extraction/FieldFilter.java
Fix for the bug that loses the SoQL fields selection if user searches for a field name.
=> preserve selected fields for SoQL construction during field search

pom.xml
use the latest SWT version available
=> use the latest SWT version available

src/main/java/com/salesforce/dataloader/config/Config.java
optimize the code to get the charset from file.encoding and jvm default
=> optimize the code to get the charset from file.encoding and jvm default

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/config/LastRun.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/main/java/com/salesforce/dataloader/ui/LoaderWindow.java, src/test/java/com/salesforce/dataloader/TestBase.java
refactoring and more encapsulation of Config and related code.
=> refactoring and more encapsulation of Config and related code

src/main/java/com/salesforce/dataloader/util/OAuthBrowserLoginRunner.java
Change OAuth browser launch logic to use xdg-open command for linux before trying browser-specific commands.
=> fix for issue #514

pom.xml, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
Check for a SWT jar file in CLASSPATH environment variable if SWT jar is not found in the installation directory.
=> Fix for issue #518

pom.xml, src/main/java/com/salesforce/dataloader/action/AbstractLoadAction.java, src/main/java/com/salesforce/dataloader/action/visitor/AbstractVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/controller/Controller.java
Add "process.bulk.saveServerLoadAndRawResultsInCSV" property that when set to true will result in dataloader capturing the batches sent to server and raw results per batch from the server in csv files.
=> add troubleshooting for issue #523

release/win/bin/encrypt.bat, release/win/dataloader.bat
- use set command to set environment variables.
=> minor bat script changes

pom.xml
minor version upgrade of log4j, spring-context, and spring-jdbc
=> minor version upgrade of log4j, spring-context, and spring-jdbc

src/main/java/com/salesforce/dataloader/security/EncryptionUtil.java
minor tweaks to the usage message shown for EncrpyionUtil invocation
=> minor tweaks to the usage message shown for encrypt/decrypt utility

release/win/bin/encrypt.bat, release/win/dataloader.bat
fix based on solution described at https://superuser.com/questions/119610/spaces-and-parenthesis-in-windows-path-variable-screws-up-batch-files
=> fix for issue #523 caused by space and braces in JAVA_HOME and PATH env vars

src/main/java/com/salesforce/dataloader/config/Config.java
Distinguish read-only properties from modifiable properties to avoid overwriting them when data loader code saves properties in config.properties file.
=> distinguish read-only properties from modifiable properties

src/main/java/com/salesforce/dataloader/config/Config.java
comments about types of properties and how they are loaded and saved
=> comments about types of properties and how they are loaded and saved

src/main/java/com/salesforce/dataloader/config/Config.java
comments regarding how properties are loaded, set, and saved
=> comments regarding how properties are loaded, set, and saved

release/win/bin/encrypt.bat, release/win/dataloader.bat, release/win/initialize.bat
refactor dataloader.bat and encrypt.bat code so that variable settings, banner display, and java version check are performed in initialize.bat script, which is invoked from dataloader.bat and encrypt.bat.
=> refactor bat code

release/win/bin/encrypt.bat, release/win/bin/process.bat, release/win/dataloader.bat, release/win/install.bat
- put double-quotes around variables that may contain a space character in its value
- code reuse - display banner in install.bat using the banner function in util.bat
=> bat script cleanup

release/win/bin/encrypt.bat, release/win/bin/process.bat, release/win/dataloader.bat, release/win/install.bat, release/win/util/util.bat
- Calling script may or may not decide to pause if java version check fails.
- Changes to the displayed error message when java version check fails.
=> bat script changes

release/win/install.bat
- use labels as functions by invoking "CALL" instead of "GOTO" whenever possible.
- factor common code for creating desktop and start menu shortcuts.
=> refactor install.bat code and make it more modular

release/win/install.bat
refactor the code for user prompt and invoke it to prompt for installation folder and creating start menu/dekstop shortcuts.
=> code refactoring and modularization

pom.xml
- using WSC 56.0.0
- patch update for google gson
- patch update for junit4
=> checking for data loader v56.0.0

src/test/java/com/salesforce/dataloader/TestBase.java
- Using Data Loader's utilities to get the URLs for authentication, SOAP service endpoint, and REST service endpoint.
- Retrying connection with previous API version if current API version does not work.
- Number of retries in establishing connection varies depending on whether the failure is due to flaky connection vs API version failure.
=> test improvements

src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java, src/main/resources/messages.properties
added message for a missing row result.
=> added message for a missing row result.

src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/PartnerLoadVisitor.java
- use the same ArrayList to store DAO rows for Partner and Bulk operations.
- use DAO in variable names to indicate that the variable is used to store a DAO value.
=> code refactoring of data structures used to store DAO rows

pom.xml
=> update mockito version

src/main/java/com/salesforce/dataloader/client/PartnerClient.java
Part of the fix for W-11992055 - Do not trace login requests to avoid logging password in plaintext.
=> Part of the fix for W-11992055 - Do not trace login requests to avoid logging credentials

release/samples/conf/process-conf.xml, src/main/java/com/salesforce/dataloader/config/Config.java
Part of the fix for W-11992055 - tracing is set to off in the sample process-conf.xml.
=> Part of the fix for W-11992055 - configure tracing to be off by default

pom.xml
=> update version to 56.0.6

pom.xml
- WSC upgrade to 57.0.0
- Minor version upgrade of mockito-core library
=> data loader version upgrade to 57.0.0

src/main/java/com/salesforce/dataloader/ui/MappingDialog.java
As requested at https://ideas.salesforce.com/s/idea/a0B8W00000MLYT3UAP/search-functionality-in-data-loader, added search field to narrow down Salesforce fields to map to.
=> search by salesforce field in mapping dialog

pom.xml
=> pom updates for v57.0.1

src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
As requested at https://ideas.salesforce.com/s/idea/a0B8W00000GdYUYUA3/phone-number-format-incorrect
=> convert to correct phone format during uploads

src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/util/DAORowUtil.java, src/test/java/com/salesforce/dataloader/util/DAORowUtilTest.java
move the code to format phone numbers to utility and add related tests
=> move the code to format phone numbers to utility and add related tests

src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/mapping/LoadMapper.java, src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/java/com/salesforce/dataloader/ui/mapping/MappingDropActionDialog.java, src/main/java/com/salesforce/dataloader/ui/mapping/MappingDropAdapter.java, src/main/java/com/salesforce/dataloader/ui/mapping/SforceDropAdapter.java, src/main/resources/labels.properties, src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java, src/test/resources/testfiles/data/oneToManySforceFieldsMappingInCsv.csv, src/test/resources/testfiles/data/oneToManySforceFieldsMappingInCsvMap.sdl
support mapping one column to multiple salesforce fields during upload operations (insert, update, upsert) as requested at https://ideas.salesforce.com/s/idea/a0B8W00000GdZVNUA3/data-loader-map-one-column-to-multiple-fields
=> support mapping of one column to multiple salesforce fields

src/main/java/com/salesforce/dataloader/mapping/Mapper.java
The issue is caused by setting mappings before populating entity fields in Mapper class constructor. The fix is to set mappings after populating entity fields.
=> fix for issue #597

pom.xml, src/main/java/com/salesforce/dataloader/mapping/Mapper.java
avoid NPE if a column name is missing in CSV file
=> avoid NPE if a column name is missing in CSV file

src/main/java/com/salesforce/dataloader/ui/SettingsPage.java
go to the next page if login was successful.
=> go to the next page if login was successful.

src/main/java/com/salesforce/dataloader/mapping/Mapper.java, src/test/resources/testfiles/data/constantMappingInCsvMap.sdl
Fix for an NPE in Mapper.java and an associated test failure
=> Fix for an NPE in Mapper.java and an associated test failure

src/main/java/com/salesforce/dataloader/action/AbstractAction.java, src/main/java/com/salesforce/dataloader/action/AbstractExtractAction.java, src/main/java/com/salesforce/dataloader/action/AbstractLoadAction.java, src/main/java/com/salesforce/dataloader/action/IAction.java, src/main/java/com/salesforce/dataloader/action/visitor/AbstractVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkApiVisitorUtil.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/IVisitor.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/test/java/com/salesforce/dataloader/process/CsvProcessAttachmentTest.java
additional check to verify that attachments are reset between batches in a bulk v1 job.
=> enhance CsvProcessAttachmentTest

pom.xml, src/main/resources/labels.properties
Relabel "Data Loader" as "Salesforce Data Loader", "salesforce.com" as "Salesforce, Inc.". and specify Permissions and Application-Name attributes in MANIFEST.MF.
=> minor tweaks to labels

release/mac/util/util.sh, release/win/util/util.bat
changes to utility scripts on windows and mac.
=> changes to utility scripts on windows and mac

release/win/bin/process.bat, release/win/dataloader.bat
minor tweaks to process.bat and dataloader.bat
=> minor tweaks to process.bat and dataloader.bat

src/main/java/com/salesforce/dataloader/install/Installer.java
- Avoid NPE in case user hits <return> without entering "yes" or "no" to a prompt.
- Create Salesforce directory in Windows Start Menu folders if it does not exist.
=> minor tweaks in java-based installer

pom.xml, src/main/java/com/salesforce/dataloader/install/Installer.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java, src/main/resources/messages.properties
use message.properties for user prompts during installation
=> use message.properties for user prompts during installation

extractSWTJar.xml, src/main/java/com/salesforce/dataloader/util/AppUtil.java
Make Data Loader jar self-contained artifact by packaging SWT jar files inside Data Loader jar.
=> package SWT jar files inside Data Loader jar.

extractSWTJar.xml, src/main/java/com/salesforce/dataloader/install/Installer.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java
extract installation artifacts during run if they are missing
=> extract installation artifacts during run if they are missing

src/main/java/com/salesforce/dataloader/install/Installer.java
parameterize symlink creation to control deletion of existing symlink.
=> minor tweak to code that creates symlink

pom.xml, src/main/java/com/salesforce/dataloader/util/AppUtil.java, src/main/resources/win/bin/encrypt.bat
fix minor issues in encrypt.bat and running process.bat with shaded jar.
=> fix minor issues in encrypt.bat and running process.bat with shaded jar.

src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java
=> refactor run.mode setting

src/main/resources/messages.properties
Fix display of the default install directory
=> Fix display of the default install directory

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java, src/main/java/com/salesforce/dataloader/util/LoggingUtil.java
- use file.separator system property to assemble name of the default config directory
- compare canonical names of classes to fetch the requested logging appender
=> minor fixes to logging

src/main/java/com/salesforce/dataloader/util/LoggingUtil.java
reduce the log level of the message about log initialization
=> reduce the log level of the message about log initialization

src/main/java/com/salesforce/dataloader/mapping/SOQLMapper.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionSOQLPage.java
Bug: unable to display extraction wizard step 2 if switching from Load (e.g. Insert) wizard after logging in.
=> a bug fix in Extraction page

src/main/java/com/salesforce/dataloader/ui/Grid12.java, src/main/java/com/salesforce/dataloader/ui/OAuthLoginDefaultControl.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionSOQLPage.java
switch OAuth env dropdown from CCombo to Combo for native look & feel
=> switch OAuth env dropdown from CCombo to Combo for native look & feel

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/ui/DataSelectionPage.java, src/main/java/com/salesforce/dataloader/ui/EntitySelectionListViewerUtil.java, src/main/java/com/salesforce/dataloader/ui/LoadPage.java, src/main/java/com/salesforce/dataloader/ui/LoaderWizardDialog.java, src/main/java/com/salesforce/dataloader/ui/OperationPage.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionDataSelectionPage.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionPage.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionSOQLPage.java, src/main/java/com/salesforce/dataloader/ui/uiActions/OperationUIAction.java, src/main/resources/labels.properties
- Set same width and height for all wizard pages and make them configurable.
- Reduce white space in wizard pages to fit more content.
- Rearrange soql wizard page layout to fit the width used for other wizard pages.
- Minor changes to generated soql for better readability.
=> mitigate issue #647

src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionSOQLPage.java
make the fields to construct WHERE condition same size for better aesthetic.
=> cosmetic changes to SoQL page in Extract wizard

pom.xml, release/install/install.command
- upgrade mockito-core from 5.2.0 to 5.3.0
- remove unused build.year property
- enable command line options passing for windows installation script
=> minor changes

pom.xml
- upgrade spring-context from 5.3.26 to 5.3.27 to address CVE-2023-20863
=> upgrade to spring-context 5.3.27

pom.xml
upgrade spring-jdbc from 5.3.26 to 5.3.27
=> upgrade spring-jdbc from 5.3.26 to 5.3.27

pom.xml, src/main/java/com/salesforce/dataloader/install/Installer.java, src/main/resources/linux/dataloader.sh, src/main/resources/linux/util/util.sh
GUI mode on Linux was not working due to a bug in installer.
=> Fix a bug with GUI mode in Linux 

README.md
=> v58 related changes to README.md

README.md
=> README content tweaks

README.md
=> tweak README content

README.md
=> content tweaks

README.md
section on what to do when reporting an issue
=> section on what to do when reporting an issue

README.md
minor changes to "reporting an issue" section
=> minor changes to "reporting an issue" section

README.md
further clarification on how to set log level to debug
=> further clarification on how to set log level to debug

README.md
=> minor content change

src/main/java/com/salesforce/dataloader/ui/DataSelectionDialog.java
formatting fix in displaying relevant settings information
=> formatting fix in displaying relevant settings information

src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/java/com/salesforce/dataloader/ui/MappingPage.java, src/main/resources/labels.properties
Show the current field mapping file so that the user understands how the mappings are  made when field mappings are pre-populated when Mappings step is displayed.
=> show name of the current field mapping file

src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/java/com/salesforce/dataloader/ui/MappingPage.java, src/main/resources/labels.properties
- labelling tweaks
- close edit map dialog after user saves the map in a file
=> mapping page and dialog minor tweaks

src/main/java/com/salesforce/dataloader/util/DateOnlyCalendar.java, src/test/java/com/salesforce/dataloader/dyna/DateConverterTest.java
When the date is during DST, the imported date becomes one day earlier.
=> Fix DST time offset calculation

pom.xml, src/test/java/com/salesforce/dataloader/dyna/DateConverterTest.java
minor change to tests for DateOnlyConverter.
=> minor change to tests for DateOnlyConverter.

pom.xml
pom cleanup - remove unused property
=> pom cleanup - remove unused property

src/main/java/com/salesforce/dataloader/action/visitor/BulkApiVisitorUtil.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkClientConnection.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkV1Connection.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkV1QueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkV2Connection.java, src/main/java/com/salesforce/dataloader/client/BulkV1Client.java, src/main/java/com/salesforce/dataloader/client/BulkV2Client.java, src/main/java/com/salesforce/dataloader/client/ClientBase.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/test/java/com/salesforce/dataloader/TestBase.java
Rename Bulk V1 related classes and methods for clarity
=> Rename Bulk V1 related classes and methods for clarity

src/test/java/com/salesforce/dataloader/TestBase.java
[client name change for data loader tests](https://github.com/forcedotcom/dataloader/commit/37cd7e3c84feda5bcfd762a457e74f71a83de322)
=> client name change for data loader tests

pom.xml, runtests.sh
Use maven verify phase for integration tests instead of a profile (integration-test).
=> streamline pom.xml for running unit and integration tests

runtests.sh
use the same approach outlined in test wiki - https://github.com/forcedotcom/dataloader/wiki/Testing-Dataloader
=> minor cleanup in runtests.sh

src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java
re-enable tests that were skipped to test the fix checked in PR #696
=> re-enable tests that were skipped to test the fix checked in PR #696

src/test/java/com/salesforce/dataloader/dao/RichTextHTMLEncodingTest.java
rename the test to verify RichText HTML encoding
=> rename the test to verify RichText HTML encoding

src/test/java/com/salesforce/dataloader/dao/RichTextHTMLEncodingTest.java
add more checks for HTML encoding correctness
=> add more checks for HTML encoding correctness

src/test/java/com/salesforce/dataloader/dao/RichTextHTMLEncodingTest.java
additional testing of HTML encoding in RichText fields
=> additional testing of HTML encoding in RichText fields

src/main/java/com/salesforce/dataloader/ui/EntitySelectionListViewerUtil.java
Resize the list showing sobjects to wizard width if the wizard width changes.
=> Resize the list showing sobjects to wizard width

src/main/java/com/salesforce/dataloader/action/AbstractLoadAction.java, src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileReader.java
- better encapsulation of DaoLoadVisitor.initLoadRateCalculator() method
- open the CSV file if not open in CSVFileReader.getTotalRows()
=> improvements around load rate calculator

src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
log the server API invocation count when exiting
=> log the server API invocation count when exiting

src/test/java/com/salesforce/dataloader/dao/CsvTest.java
additional tests for CSV delimiters settings for
- query results
- upload
- upload status
=> additional tests for CSV delimiters

src/test/java/com/salesforce/dataloader/dao/CsvTest.java
more tests for CSV file reading
=> more tests for CSV file reading

src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
- check for non-null logger to avoid NPE
- avoid depricated constructor for WildcardFileFilter
=> minor code cleanup of DataLoaderRunner

pom.xml, src/main/resources/contrib/installjava.bat, src/main/resources/contrib/installjava.command
- Addition of Java installation scripts in contrib folder
- Exclusion of contrib folder content from jar
=> unsupported scripts to install Java

src/main/resources/mac/util/util.sh, src/main/resources/win/util/util.bat
- run shell-specific .profile and .rc files in util.sh for mac and linux to correctly set up user environment variables.
- remove incorrect comments from util.bat for windows.
=> minor cleanup of util scripts

src/main/resources/mac/util/util.sh
- run shell-specific .profile and .rc files in util.sh for mac and linux to correctly set up user environment variables.
=>  run .profile and .rc files in util.sh for mac and linux

src/main/java/com/salesforce/dataloader/install/Installer.java
check for installation artifacts instead of creating a dot file to determine if installation is needed.
=> check for installation artifacts instead of creating a dot file

src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java, src/test/resources/testfiles/data/emptyFirstRowFieldValueInCsvMap.sdl, src/test/resources/testfiles/data/emptyFirstRowFieldValueInCsvTemplate.csv
added test to detect regression W-13612705
=> added test to detect regression W-13612705

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/resources/labels.properties
=> tooltip for KeepAccountOwner

.github/dependabot.yml
perform daily check of dependency updates
=> perform daily check of dependency updates

src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/main/java/com/salesforce/dataloader/ui/DataSelectionDialog.java
Remove Controller.initializeOperationAndCreateMapper() and createMapperPostInitialize() methods as Controller.initialize() can set up mapper in its implementation.
=> minor code refactoring of Controller.java

src/main/java/com/salesforce/dataloader/mapping/CaseInsensitiveSet.java, src/main/java/com/salesforce/dataloader/mapping/LoadMapper.java, src/main/java/com/salesforce/dataloader/mapping/Mapper.java
Keep the field order the same as specified in the upload CSV.
=> preserve the upload field order in CSV

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/ui/BaseDialog.java, src/main/java/com/salesforce/dataloader/ui/CSVChooserDialog.java, src/main/java/com/salesforce/dataloader/ui/DataSelectionDialog.java, src/main/java/com/salesforce/dataloader/ui/HyperlinkDialog.java, src/main/java/com/salesforce/dataloader/ui/LoadFinishDialog.java, src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionDataSelectionDialog.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionFinishDialog.java
Created base class, BaseDialog.java, to capture refactored code and make AdvancedSettingsDialog, CSVChooserDialog, DataSelectionDialog, ExtractionDataSelectionDialog, ExtractionFinishDialog, HyperlinkDialog, LoadFinishDialog, and MappingDialog subclasses of BaseDialog.
=> refactor dialog code

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java
Issue was introduced in PR #749.
=> fix bug - can't select "Use Bulk API" checkbox after unchecking it

src/main/java/com/salesforce/dataloader/mapping/CaseInsensitiveSet.java, src/main/java/com/salesforce/dataloader/mapping/LoadMapper.java, src/main/java/com/salesforce/dataloader/mapping/Mapper.java
code changes in PR #774 are causing a number of tests to break. Reverting the changes to avoid the breakage.
=> revert the changes introduced in PR #774

src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/java/com/salesforce/dataloader/ui/mapping/MappingDropActionDialog.java
=> refactor code in MappingDropActionDialog

src/main/java/com/salesforce/dataloader/ui/DataSelectionDialog.java
refactor the code to process errors in reading from CSV file.
=> refactor the code to process errors in reading from CSV file

src/main/java/com/salesforce/dataloader/install/Installer.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/java/com/salesforce/dataloader/ui/CSVViewerDialog.java, src/main/java/com/salesforce/dataloader/ui/HyperlinkDialog.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java, src/main/resources/messages.properties
refactor the code to launch an external command
=> refactor the code to launch an external command

pom.xml
version number change to v59.0.0
=> version number change to v59.0.0

src/test/java/com/salesforce/dataloader/client/PartnerClientTest.java
test that data loader handles uncompressed request/response.
=> test the fix for W-10656724

src/test/java/com/salesforce/dataloader/TestSetting.java, src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java
tests for Bulk v1 ops when compression is disabled
=> tests for Bulk v1 ops when compression is disabled

runtests.sh
- discover and specify full jar name for -cp param
- debug password encryption if -d is specified
- no keyfile is specified by default
=> tweaks to test script

src/main/java/com/salesforce/dataloader/util/OAuthBrowserLoginRunner.java
retry browser-based OAuth login with my.salesforce.com and login.salesforce.com URLs.
=> mitigate the issue in discussion #800

src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserLoginRunner.java
minor code cleanup in using auth endpoint URL string constants
=> minor code cleanup in using auth endpoint URL string constants

src/main/java/com/salesforce/dataloader/client/DescribeRefObject.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/dyna/SObjectReference.java, src/main/java/com/salesforce/dataloader/ui/ForeignKeyExternalIdPage.java, src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/java/com/salesforce/dataloader/ui/MappingPage.java, src/main/java/com/salesforce/dataloader/ui/mapping/SforceLabelProvider.java, src/main/resources/labels.properties
Show parent object's field name, field label, and name of the parent object if the field represents a relationship field.
=> show more parent object field info in Field Mapping Dialog

src/main/java/com/salesforce/dataloader/client/DescribeRefObject.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/ui/mapping/SforceLabelProvider.java
cap the number of server calls to 5 for fields with multiple parents.
=> cap the number of server calls for fields with multiple parents

runtests.sh
skip "mvn clean" unless -c option provided
=> skip "mvn clean" unless -c option provided

src/main/java/com/salesforce/dataloader/client/PartnerClient.java
Log additional details to help troubleshoot if an ApiFault is encountered.
=> log additional details if an ApiFault is encountered

src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/client/ClientBase.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/client/SessionInfo.java, src/main/java/com/salesforce/dataloader/controller/Controller.java
- Store UserInfoResult as a field in SessionInfo object.
- Use UserInfoResult.getSessionSecondsValid() in determining isSessionValid()
- Add method SessionInfo.performedSessionActivity() that updates the last activity time and is invoked when Controller performs a server-side operation.
=> code cleanup around session timeout

src/main/java/com/salesforce/dataloader/action/OperationInfo.java, src/main/java/com/salesforce/dataloader/action/OperationInfoUIHelper.java, src/main/java/com/salesforce/dataloader/action/UndeleteAction.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkApiVisitorUtil.java, src/main/java/com/salesforce/dataloader/action/visitor/PartnerLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/UndeleteVisitor.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/ui/DataSelectionPage.java, src/main/java/com/salesforce/dataloader/ui/LoadWizard.java, src/main/java/com/salesforce/dataloader/ui/LoaderWindow.java, src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/resources/labels.properties, src/main/resources/messages.properties, src/test/java/com/salesforce/dataloader/process/CsvExtractAllProcessTest.java, src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java
issue reported at https://ideas.salesforce.com/s/idea/a0B8W00000Gdc1nUAB/allow-data-loader-to-undelete-records
=> support undelete to address the issue of accidental delete

src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
test to verify undelete operation
=> test to verify undelete operation

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java
do not auto-logout when config changes
=> do not auto-logout when config changes

src/main/java/com/salesforce/dataloader/ui/LoadWizard.java, src/main/resources/labels.properties
minor tweaks to dialog and wizard page text for readability
=> minor tweaks to dialog and wizard page text for readability

src/main/java/com/salesforce/dataloader/action/AbstractExtractAction.java, src/main/java/com/salesforce/dataloader/mapping/SOQLMapper.java
Fix the error: 'Error opening CSV file for writing: header row (with column names) has to be provided' when switching from 'skip local validation of the query' to not skip without closing the Export wizard.
=> fix error when unchecking 'skip local validation of the query'

src/main/java/com/salesforce/dataloader/action/AbstractExtractAction.java, src/main/java/com/salesforce/dataloader/action/OperationInfo.java, src/main/java/com/salesforce/dataloader/mapping/CaseInsensitiveMap.java, src/main/java/com/salesforce/dataloader/mapping/SOQLMapper.java
fix test failures in extraction and hard delete tests
=> fix test failures in extraction and hard delete tests

src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/mapping/SOQLMapper.java
- Use the same logic for field mapping regardless of determining soql result fields based on soql query or based on returned results.
- Comments to clarify SOQLMapping implementation outline.
=> code cleanup in SOQLMapper class

src/main/java/com/salesforce/dataloader/dao/DataWriter.java, src/main/java/com/salesforce/dataloader/dao/database/DatabaseWriter.java
add the method to get sobject field names from a data row during data extraction.
=> add the method to get field names from a data row to write

src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java
add test for soql queries that don't have an explicit field list
- run "select fields(standard) from Account" for SOAP requests
=> add test for soql queries that don't have an explicit field list

src/test/java/com/salesforce/dataloader/TestBase.java, src/test/java/com/salesforce/dataloader/process/CsvExtractProcessTest.java, src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java, src/test/resources/testfiles/data/selectFieldsSoqlMap.sdl
test for deriving output fields from soql results in bulk v2.
=> test for deriving output fields from soql results in bulk v2

src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java, src/test/resources/testfiles/data/selectFieldsSoqlMap.sdl
additional testing for determining field names from query result
=> additional testing for determining field names from query result

pom.xml
discard redundant license and notice files from META_INF
=> discard redundant license and notice files from META_INF

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java
logout if the user changes client id (connected app) in settings dialog as the current session contains old client id.
=> logout if clientid (connected app) value changes in settings dialog

src/main/java/com/salesforce/dataloader/ui/CSVViewerDialog.java
show CSV files without header row instead of an error message
=> show CSV files without header row instead of an error message

src/test/java/com/salesforce/dataloader/PartnerConnectionForTest.java, src/test/java/com/salesforce/dataloader/TestBase.java, src/test/java/com/salesforce/dataloader/process/BulkV1CsvProcessTest.java, src/test/java/com/salesforce/dataloader/process/NAProcessTest.java, src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java, src/test/java/com/salesforce/dataloader/util/TestRecordsUtil.java
- keep an inventory of inserted sobject types
- delete all sobjects inserted by test user since test start
=> more thorough clean up of inserted sobjects for test

src/test/java/com/salesforce/dataloader/PartnerConnectionForTest.java, src/test/java/com/salesforce/dataloader/TestBase.java
perform one time cleanup during the first instantiation of integration tests.
=> integration tests - one time cleanup during the first instantiation

src/test/java/com/salesforce/dataloader/dao/RichTextHTMLEncodingTest.java
test to make sure that the code handles a HTML tags with no whitespace outside HTML tags.
=>  added test to avoid regression in the fix for W-14287051

src/test/java/com/salesforce/dataloader/dao/RichTextHTMLEncodingTest.java
Additional tests to make sure that the code handles  multiple HTML tags with no content outside HTML tags.
=> tests for multiple HTML tags w/o non-tag content in Rich Text field

src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
remove unused imports and method.
=> minor cleanup

src/main/java/com/salesforce/dataloader/client/PartnerClient.java
The code for listing idlookup fields of the parent object has 4-5 levels of nested for loops and if conditions with multiple predicates in each if statement. These are simplified by removing repeated if conditions to first determine that an sobject field is a lookup relationship field and it is createable or readable.
=> improve readability of code for listing idlookup fields of parent

src/main/java/com/salesforce/dataloader/client/PartnerClient.java
more comments and better naming for code readability
=> more comments and better naming for code readability

src/test/java/com/salesforce/dataloader/process/CsvExtractAggregateQueryProcessTest.java
added test to verify aggregate query when loader.query.limitOutputToQueryFields set to false.
=> verify aggregate query when limitOutputToQueryFields==false

updateSWT.py
fix updateSWT script to keep up with change to Eclipse download page
=> fix updateSWT script to keep up with change to Eclipse download page

pom.xml, src/main/java/com/salesforce/dataloader/ui/LoaderDownloadDialog.java, src/main/java/com/salesforce/dataloader/ui/LoaderTitleAreaDialog.java, src/main/java/com/salesforce/dataloader/ui/LoaderWindow.java, src/main/java/com/salesforce/dataloader/ui/OAuthLoginFromBrowserFlow.java, src/main/java/com/salesforce/dataloader/ui/UIUtils.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserLoginRunner.java, src/main/resources/labels.properties
Based on the ask at https://ideas.salesforce.com/s/idea/a0B8W00000GdVkgUAF/data-loader-upgrade-option-should-be-there-in-the-application-itself
- show the dialog with the link to Data Loader download page if a newer version is available for download.
=> show the dialog to upgrade data loader if newer version is available

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/ui/LoaderUpgradeDialog.java, src/main/java/com/salesforce/dataloader/ui/LoaderWindow.java, src/main/resources/labels.properties
loader.ui.showUpgrade property to show/hide upgrade dialog along with its setting in Advanced Settings dialog.
=> property to show/hide upgrade dialog

src/main/resources/labels.properties
fix the message display for CSV chooser dialog
=> fix the message display for CSV chooser dialog

src/main/java/com/salesforce/dataloader/ui/uiActions/HelpUIAction.java, src/main/resources/labels.properties
Display "You are running the latest version" message in About dialog if the user is using the latest version.
=> Display "You are running the latest version" message in About dialog

pom.xml, src/test/java/com/salesforce/dataloader/EncryptionUtil/EncryptionUtilTest.java, src/test/java/com/salesforce/dataloader/dao/database/DatabaseTest.java
- warning about deprecated api
- warning about unused package
=> fix compiler warnings

src/main/java/com/salesforce/dataloader/client/PartnerClient.java
Improve readability of setFieldReferenceDescribes() by breaking it up into smaller methods that are invoked successively.
=> improve readability of PartnerClient.setFieldReferenceDescribes()

src/main/java/com/salesforce/dataloader/ui/LoaderWindow.java
reduce chances of SWT menu not displayed when displaying upgrade screen
=> reduce chances of SWT menu not displayed when displaying upgrade screen

pom.xml
update data loader version to v60.0.0
=> update data loader version to v60.0.0

dlbuilder.sh, src/main/resources/mac/util/util.sh
util.sh warnings
- https://github.com/forcedotcom/dataloader/security/code-scanning/217
- https://github.com/forcedotcom/dataloader/security/code-scanning/222
- https://github.com/forcedotcom/dataloader/security/code-scanning/225
dlbuilder.sh warnings
- https://github.com/forcedotcom/dataloader/security/code-scanning/218
=> Changes based on Codacy code scanning warnings

runtests.sh, updateSWT.py
- remove unused variable in updateSWT.py
- avoid test execution during build phase when running tests through script
=> cleanup of utility scripts

dlbuilder.sh
Double quote to prevent globbing and word splitting.
=> minor change to utility script

runtests.sh
Quote the parameter to -name so the shell won't interpret it
=> minor change to test execution script

src/main/java/com/salesforce/dataloader/action/visitor/PartnerLoadVisitor.java
create helper methods for loadBatch() to make it easier to set additional headers in the future.
=> modularize code

src/main/java/com/salesforce/dataloader/action/AbstractAction.java, src/main/java/com/salesforce/dataloader/action/progress/NihilistProgressAdapter.java, src/main/java/com/salesforce/dataloader/action/progress/SWTProgressAdapter.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/install/Installer.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/main/java/com/salesforce/dataloader/security/EncryptionUtil.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java, src/main/java/com/salesforce/dataloader/util/ExitException.java, src/test/java/com/salesforce/dataloader/TestProgressMontitor.java
As requested at https://ideas.salesforce.com/s/idea/a0B8W00000GdojHUAR/need-return-codes-from-apex-command-line-data-loaderfor-successfailure
=> multiple exit error codes for batch (CLI) mode

src/main/java/com/salesforce/dataloader/action/visitor/AbstractQueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java
Set the progress monitor subtask at the start to show progress to the user.
=> minor improvement in showing results progress in UI

src/main/java/com/salesforce/dataloader/dyna/FileByteArrayConverter.java, src/main/java/com/salesforce/dataloader/ui/ContentLimitLink.java, src/main/java/com/salesforce/dataloader/ui/DataSelectionDialog.java, src/main/java/com/salesforce/dataloader/ui/FinishPage.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java, src/main/resources/labels.properties
refactor code including subclass Link widget to refactor code that displays content limits information page.
=> refactor code for the link to content limit info

src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/dyna/RelationshipField.java, src/test/java/com/salesforce/dataloader/PartnerConnectionForTest.java, src/test/java/com/salesforce/dataloader/client/PartnerClientTest.java, src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java, src/test/resources/testfiles/data/insertTaskWithContactAsWhoCsv.csv, src/test/resources/testfiles/data/insertTaskWithContactAsWhoCsvMap.sdl
- support polymorphic relationship mapping in Bulk
- add test for polymorphic relationship mapping
=> poloymorphic relationship support in Bulk

src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/dyna/SforceDynaBean.java, src/test/java/com/salesforce/dataloader/process/CsvProcessAttachmentTest.java, src/test/resources/testfiles/data/polymorphicRelationshipInAttachment.csv, src/test/resources/testfiles/data/polymorphicRelationshipInAttachmentMap.sdl
Support for polymorphic relations with more than 5 obj types. Add test for more than 5 parent obj types in polymorphic relationship.
=> support for polymorphic relations with more than 5 obj types

src/test/java/com/salesforce/dataloader/process/CsvProcessAttachmentTest.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java, src/test/resources/testfiles/data/polymorphicRelationshipInAttachment.csv, src/test/resources/testfiles/data/polymorphicRelationshipInAttachmentMap.sdl
Test that a CSV file can contain records that map a relationship field to different parent types if the relationship is a polymorphic relationship.
=> additional test for polymorphic relationships

src/test/java/com/salesforce/dataloader/process/CsvProcessAttachmentTest.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
=> fix test failures

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java
uncheck "keep acct team" only if "use bulk API" is checked
=> uncheck "keep acct team" only if "use bulk API" is checked

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java
implement the following behavior:
- checking one unchecks the other
- unchecking one does not change state of the other
=> cleanup toggle between "keep acct team" and "use bulk api"

src/main/java/com/salesforce/dataloader/dyna/RelationshipField.java, src/main/java/com/salesforce/dataloader/ui/ChooseLookupFieldForRelationshipPage.java, src/main/java/com/salesforce/dataloader/ui/ExternalIdPage.java, src/main/java/com/salesforce/dataloader/ui/LoadWizard.java, src/main/resources/labels.properties
Better wording to prompt user to specify the idlookup field of related object used in CSV file.
=> minor UI tweaks for referencing relationships thru idlookup

src/test/java/com/salesforce/dataloader/dyna/DateConverterTest.java
Add more tests for European date format
=> Additional date conversion tests

src/main/java/com/salesforce/dataloader/ui/ChooseLookupFieldForRelationshipPage.java, src/main/java/com/salesforce/dataloader/ui/mapping/SforceLabelProvider.java, src/main/resources/labels.properties
UI label changes for relationship mapping step
=> UI label changes for relationship mapping step

src/main/java/com/salesforce/dataloader/dyna/DateTimeConverter.java, src/test/java/com/salesforce/dataloader/dyna/DateConverterTest.java, src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java
refactor code and additional tests for date/time format
=> refactor code and additional tests for date/time format

src/main/java/com/salesforce/dataloader/dyna/DateOnlyConverter.java, src/main/java/com/salesforce/dataloader/dyna/DateTimeConverter.java, src/test/java/com/salesforce/dataloader/dyna/DateConverterTest.java
- Remove unused constructors
- Add a test to verify 'xxx' date pattern
=> remove unused constructors

src/main/java/com/salesforce/dataloader/dyna/BooleanConverter.java, src/main/java/com/salesforce/dataloader/dyna/DoubleConverter.java, src/main/java/com/salesforce/dataloader/dyna/FileByteArrayConverter.java, src/main/java/com/salesforce/dataloader/dyna/IntegerConverter.java, src/main/java/com/salesforce/dataloader/dyna/SObjectReferenceConverter.java, src/main/java/com/salesforce/dataloader/dyna/SforceDynaBean.java, src/main/java/com/salesforce/dataloader/dyna/StringConverter.java
remove unused constructors and member variables
=> converter code cleanup

src/main/java/com/salesforce/dataloader/dao/database/DatabaseContext.java, src/main/java/com/salesforce/dataloader/dyna/DateOnlyConverter.java, src/main/java/com/salesforce/dataloader/dyna/DateTimeConverter.java, src/test/java/com/salesforce/dataloader/dyna/DateConverterTest.java
- remove wrapper constructor
- remove wrapper methods
=> code cleanup of DateTimeConverter

pom.xml, src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/PartnerLoadVisitor.java
W-14893310 - Failed record is recorded in Success log when inserting W-14887469 - Duplicate records are created when inserting
The fix also likely fixes #984
=> Fix for W-14887469 and W-14893310

src/main/java/com/salesforce/dataloader/ui/DataSelectionDialog.java, src/main/resources/labels.properties
- provide specifics of the exception thrown when reading CSV file
- provide specifics of current CSV delimiters when showing error in reading a CSV file
=> improve error messages in reading CSV file 

src/test/java/com/salesforce/dataloader/process/CsvExtractProcessTest.java, src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java
test for queries on polymorphic relationship traversals
=> test for queries on polymorphic relationship traversals

src/test/java/com/salesforce/dataloader/process/CsvExtractProcessTest.java, src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java, src/test/resources/testfiles/data/acctsWithBinaryDataInRTF.csv, src/test/resources/testfiles/data/binaryDataInRTFQueryResultMap.sdl
test for binary data inclusion in RTF query results
=> test for binary data inclusion in RTF query results

src/main/java/com/salesforce/dataloader/client/BulkV1Client.java, src/main/java/com/salesforce/dataloader/client/BulkV2Client.java, src/main/java/com/salesforce/dataloader/client/ClientBase.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/test/java/com/salesforce/dataloader/TestBase.java
code refactoring around API version to use
=> code refactoring around API version to use

src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/client/ReferenceEntitiesDescribeMap.java, src/main/java/com/salesforce/dataloader/dyna/ParentIdLookupFieldForRelationship.java, src/main/java/com/salesforce/dataloader/dyna/RelationshipParentSObject.java, src/main/java/com/salesforce/dataloader/dyna/SObjectReference.java, src/main/java/com/salesforce/dataloader/dyna/SforceDynaBean.java, src/main/java/com/salesforce/dataloader/ui/ChooseLookupFieldForRelationshipPage.java, src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java
Use RelationshipParentSObject to represent the possible parent objects in a relationship. Refactor code around this approach.
=> refactor code for relationship field

src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/client/ReferenceEntitiesDescribeMap.java, src/main/java/com/salesforce/dataloader/dyna/IdLookupHandleForRelationship.java, src/main/java/com/salesforce/dataloader/dyna/ParentObjectHandleForRelationship.java, src/main/java/com/salesforce/dataloader/dyna/SObjectReference.java, src/main/java/com/salesforce/dataloader/dyna/SforceDynaBean.java, src/main/java/com/salesforce/dataloader/ui/ChooseLookupFieldForRelationshipPage.java, src/main/java/com/salesforce/dataloader/ui/mapping/SforceLabelProvider.java, src/test/java/com/salesforce/dataloader/client/PartnerClientTest.java, src/test/java/com/salesforce/dataloader/dyna/SObjectReferenceConverterTest.java, src/test/java/com/salesforce/dataloader/process/CsvProcessAttachmentTest.java, src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java
modularize and refactor objects to represent relationships
=> modularize and refactor objects to represent relationships

src/main/java/com/salesforce/dataloader/action/visitor/BulkApiVisitorUtil.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkV1QueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkV2QueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/PartnerLoadVisitor.java, src/main/java/com/salesforce/dataloader/client/BulkV1Client.java, src/main/java/com/salesforce/dataloader/client/BulkV2Client.java, src/main/java/com/salesforce/dataloader/client/ClientBase.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/ui/AuthenticationRunner.java, src/test/java/com/salesforce/dataloader/client/PartnerClientTest.java, src/test/java/com/salesforce/dataloader/process/NAProcessTest.java
method name change to improve readability
=> method name change to improve readability

src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/client/ReferenceEntitiesDescribeMap.java, src/main/java/com/salesforce/dataloader/dyna/ParentIdLookupFieldString.java, src/main/java/com/salesforce/dataloader/dyna/ParentSObjectString.java, src/main/java/com/salesforce/dataloader/dyna/SObjectReference.java, src/main/java/com/salesforce/dataloader/dyna/SforceDynaBean.java, src/main/java/com/salesforce/dataloader/ui/ChooseLookupFieldForRelationshipPage.java, src/main/java/com/salesforce/dataloader/ui/mapping/SforceLabelProvider.java, src/test/java/com/salesforce/dataloader/client/PartnerClientTest.java, src/test/java/com/salesforce/dataloader/dyna/SObjectReferenceConverterTest.java
Rename representation strings related to relationship fields
=> Rename representation strings related to relationship fields

rundl.sh
script to run data loader from git clone root folder using locally built jar in target folder.
=> script to run data loader from git clone root folder

rundl.sh
add option -e to encrypt a string
=> add option -e to encrypt a string

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java
fix for issue #1011 - use process bean name specified in process-conf.xml as the prefix for lastrun.properties file.
=> fix for issue #1011

src/main/resources/mac/encrypt.sh
Has the same behavior as encrypt.bat on Windows.
=> encrypt.sh wrapper for mac and linux

src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/client/ReferenceEntitiesDescribeMap.java, src/main/java/com/salesforce/dataloader/dyna/ParentIdLookupFieldFormatter.java, src/main/java/com/salesforce/dataloader/dyna/ParentSObjectFormatter.java, src/main/java/com/salesforce/dataloader/dyna/SforceDynaBean.java, src/main/java/com/salesforce/dataloader/ui/ChooseLookupFieldForRelationshipPage.java
refactoring - do not carry relationship cardinality in ParentSObjectFormatter.
=> code refactoring

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/ui/OperationPage.java
- Remove unused method, loginIfSessionExists(), in Controller.java
- Do not increase wizard page shell size by 1 pixel in OperationPage.java
- Provide reference to bulkv1 and bulkv2 limits in comments in Config.java
=> minor code cleanup

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/ui/DataSelectionDialog.java, src/test/java/com/salesforce/dataloader/process/CsvExtractProcessTest.java
Fix test failure in checking lastrun.properties prefix
Show bulk v2 upload job size limit in wizard steps and show it as readable setting if bulk v2 checkbox is checked.
=> code cleanup

src/main/java/com/salesforce/dataloader/config/Config.java
remove the prefix "pilot" from Bulk v2 config property
=> remove the prefix "pilot" from Bulk v2 config property

src/main/java/com/salesforce/dataloader/action/visitor/BulkApiVisitorUtil.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkV2Connection.java
bulk v2 upload uses a temporary staging file for upload that is unnecessary. the change is to bypass the staging file creation and use.
=> bulk v2 optimization - eliminate staging file for upload

src/main/java/com/salesforce/dataloader/ui/DLProgressMonitorDialog.java, src/main/java/com/salesforce/dataloader/ui/LoadWizard.java
Make progress monitor dialog resizable to fix issue #1028
=> fix for issue #1028 - resizable progress dialog

src/main/java/com/salesforce/dataloader/ui/LoaderWindow.java, src/main/java/com/salesforce/dataloader/ui/LoaderWizardDialog.java, src/main/java/com/salesforce/dataloader/ui/OperationPage.java, src/main/java/com/salesforce/dataloader/ui/SettingsPage.java
Calculate and set width and height of wizard steps instead of presetting them to fixed value.
=> fix for issue #1017

updateSWT.py
python script improvement - use built-in which() method
=> python script improvement - use built-in which() method

src/main/java/com/salesforce/dataloader/action/visitor/BulkApiVisitorUtil.java
the count of processed records and failed records in bulk job info object does not get updated if entire batch fails on server side. Add a wrapper for counting total processed records and total failed records to show progress in such scenarios.
=> wrapper to show progress in processing bulk upload jobs

src/main/resources/labels.properties
=> Settings label tweak

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionSOQLPage.java
- vertical and horizontal resize of extraction soql page
- vertical resize of Settings page
=> fix resize issues reported in issue #1017

src/main/java/com/salesforce/dataloader/ui/EntitySelectionListViewerUtil.java, src/main/java/com/salesforce/dataloader/ui/OperationPage.java
code cleanup - fix issue introduced in PR #1040
=> code cleanup - fix issue introduced in PR #1040

src/main/java/com/salesforce/dataloader/ui/UsernamePasswordLoginStandardControl.java
fix issue of showing incomplete login error text
=> fix issue of showing incomplete login error text

src/main/java/com/salesforce/dataloader/ui/BaseWizard.java, src/main/java/com/salesforce/dataloader/ui/LoadWizard.java, src/main/java/com/salesforce/dataloader/ui/LoginPage.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionWizard.java
Rename the UI page for login from SettingsPage.java to LoginPage.java.
=> rename the UI page for login

src/main/java/com/salesforce/dataloader/ui/OAuthFlow.java
Remove use of Grid12 for layout setting in OAuthFlow dialog
=> Remove use of Grid12 for layout setting in OAuthFlow dialog

src/main/java/com/salesforce/dataloader/ui/BaseDialog.java, src/main/java/com/salesforce/dataloader/ui/DataSelectionPage.java, src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/java/com/salesforce/dataloader/ui/MappingPage.java, src/main/java/com/salesforce/dataloader/ui/UIUtils.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionDataSelectionPage.java
- Expand columns in Mapping page and Mapping dialog to capture extra page width
- Tweak to optimize display of sobjects in data selection page
- Use wizard page dimensions as Mapping dialog dimensions
=> fix for issue #1049

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/ui/DataSelectionPage.java, src/main/java/com/salesforce/dataloader/ui/EntitySelectionListViewerUtil.java, src/main/java/com/salesforce/dataloader/ui/LoaderWizardDialog.java, src/main/java/com/salesforce/dataloader/ui/LoginPage.java, src/main/java/com/salesforce/dataloader/ui/OperationPage.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionDataSelectionPage.java
- retain resize choice across wizard steps and across multiple wizard invocations in a session.
=> resize wizard improvements

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/ui/LoaderWindow.java, src/main/java/com/salesforce/dataloader/ui/LoaderWizardDialog.java, src/main/java/com/salesforce/dataloader/ui/OperationPage.java
Save wizard location info if the user moves the wizard so that user does not have to move it again when relaunching the wizard.
=> persist wizard location

src/main/resources/labels.properties
label change for wizard width and height settings in Settings dialog
=> label change in Settings dialog

src/main/java/com/salesforce/dataloader/ui/LoaderWizardDialog.java, src/main/java/com/salesforce/dataloader/ui/LoginPage.java, src/main/java/com/salesforce/dataloader/ui/UsernamePasswordLoginControl.java
- remove unused variables from LoaderWizardDialog
- center username, password login controls for better visibility
=> minor UI cleanup

src/main/java/com/salesforce/dataloader/config/Config.java
change default wizard width from 400 to 600 pixels
=> change to default wizard width

src/main/java/com/salesforce/dataloader/ui/UIUtils.java, src/main/java/com/salesforce/dataloader/ui/UsernamePasswordLoginControl.java
cosmetic change to login button size
=> cosmetic change to login button size

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/ui/BaseDialog.java, src/main/java/com/salesforce/dataloader/ui/LoaderWizardDialog.java, src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/java/com/salesforce/dataloader/ui/MappingPage.java, src/main/java/com/salesforce/dataloader/ui/OperationPage.java, src/main/java/com/salesforce/dataloader/ui/UIUtils.java
persist dimensions of MappingDialog
=> persist dimensions of MappingDialog

src/main/java/com/salesforce/dataloader/ui/UIUtils.java
use wizard dimensions as initial settings for dialog dimensions
=> use wizard dimensions as initial settings for dialog dimensions

src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/java/com/salesforce/dataloader/ui/OperationPage.java
immediately persist changes to wizard page mapping dialog dimensions
=> immediately persist changes to wizard page mapping dialog dimensions

src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/java/com/salesforce/dataloader/ui/OperationPage.java
do not persist wizard and dialog size info unless they are visible
=> do not persist wizard and dialog size info unless they are visible

src/main/java/com/salesforce/dataloader/ui/UsernamePasswordLoginControl.java
fix to show full error message when login attempt fails
=> fix to show full error message when login attempt fails

src/main/java/com/salesforce/dataloader/ui/BaseDialog.java, src/main/java/com/salesforce/dataloader/ui/DataSelectionDialog.java
consolidate open() method in BaseDialog.
=> refactoring dialog code

src/main/java/com/salesforce/dataloader/ui/BaseDialog.java
cosmetic change to location of dialogs
=> cosmetic change to location of dialogs

src/main/java/com/salesforce/dataloader/ui/MappingDialog.java
refactor code to calculate optimal table column size
=> refactor code to calculate optimal table column size

src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/java/com/salesforce/dataloader/ui/MappingPage.java, src/main/java/com/salesforce/dataloader/ui/UIUtils.java
simplify and refactor table column sizing code
=> simplify and refactor table column sizing code

src/main/java/com/salesforce/dataloader/ui/LoaderWindow.java, src/main/java/com/salesforce/dataloader/ui/WelcomeScreenDialog.java
class name change to be consistent with property settings.
=> class name change from LoaderTitleDialog to WelcomeScreenDialog

src/main/java/com/salesforce/dataloader/ui/LoginPage.java
fix incorrectly sized Data Selection viewer on Mac
=> fix incorrectly sized Data Selection viewer on Mac

src/main/java/com/salesforce/dataloader/install/Installer.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
code to be able to install without prompting
=> code to be able to install without prompting

release/install/install.command, src/main/java/com/salesforce/dataloader/install/Installer.java, src/main/resources/messages.properties
- have same prompt at end of interactive installation on windows and mac.
- no prompt at end of non-interactive installation.
=> minor installation tweaks

src/main/java/com/salesforce/dataloader/oauth/OAuthFlowUtil.java, src/main/java/com/salesforce/dataloader/oauth/OAuthSecretFlowUtil.java, src/main/java/com/salesforce/dataloader/ui/OAuthFlow.java, src/main/java/com/salesforce/dataloader/ui/OAuthSecretFlow.java, src/main/java/com/salesforce/dataloader/ui/OAuthTokenFlow.java, src/test/java/com/salesforce/dataloader/oauth/OAuthFlowUtilTests.java, src/test/java/com/salesforce/dataloader/oauth/OAuthSecretFlowUtilTests.java, src/test/java/com/salesforce/dataloader/util/AppUtilTest.java
Decoupled OAuth protocol related code from UI aspects by introducing OAuthFlowUtil.java and OAuthSecretFlowUtil.java. Renamed related tests.
=> refactor OAuth code and related tests

src/main/java/com/salesforce/dataloader/dao/csv/CSVFileWriter.java
Do not capitalize column headers of SOQL results
=> fix for #1095

src/main/java/com/salesforce/dataloader/action/visitor/RESTTest.java
=> minor bug fix

src/main/java/com/salesforce/dataloader/action/UpdateAction.java, src/main/java/com/salesforce/dataloader/action/visitor/RESTUpdateVisitor.java, src/main/java/com/salesforce/dataloader/client/BulkV1Client.java, src/main/java/com/salesforce/dataloader/client/BulkV2Client.java, src/main/java/com/salesforce/dataloader/client/ClientBase.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/client/RESTClient.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/controller/Controller.java
Data Loader uses Partner SOAP and Bulk REST APIs. This PR sets the foundation for being able to make REST API calls, specifically Composite REST calls which are similar to Partner SOAP to be able to support newer capabilities offered by Salesforce APIs.
=> supporting classes to use REST API

src/main/java/com/salesforce/dataloader/action/visitor/BulkV2Connection.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java
refactor code for object/json conversion
=> refactor code for object/json conversion

src/main/java/com/salesforce/dataloader/action/visitor/RESTLoadVisitor.java, src/main/java/com/salesforce/dataloader/client/CompositeRESTClient.java, src/main/java/com/salesforce/dataloader/client/SObject4JSON.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/dyna/SObjectReference.java, src/main/java/com/salesforce/dataloader/dyna/SforceDynaBean.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java, src/test/java/com/salesforce/dataloader/dyna/SObjectReferenceConverterTest.java
Data Loader uses Partner SOAP and Bulk REST APIs. This PR adds to the foundation for being able to make REST API calls, specifically Composite REST calls which are similar to Partner SOAP to be able to support newer capabilities offered by Salesforce APIs.
=> [work in progress] support for Composite REST

src/main/java/com/salesforce/dataloader/client/CompositeRESTClient.java
minor tweak to composite rest implementation - use URL path used for upserts.
=> minor tweak to composite rest implementation

src/main/java/com/salesforce/dataloader/action/AbstractLoadAction.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkApiVisitorUtil.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/ui/DataSelectionDialog.java, src/main/java/com/salesforce/dataloader/ui/LoadPage.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionPage.java, src/main/resources/labels.properties, src/test/java/com/salesforce/dataloader/process/BulkV1CsvProcessTest.java, src/test/java/com/salesforce/dataloader/process/CsvEncodingProcessTest.java, src/test/java/com/salesforce/dataloader/process/CsvProcessAttachmentTest.java, src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java, src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java
relabel load and export batch size parameter names and constants
=> relabel load and export batch size parameter names and constants

pom.xml
update WSC version from 61.0.0 to 61.1.0
=> update WSC version from 61.0.0 to 61.1.0

src/main/java/com/salesforce/dataloader/action/visitor/BulkApiVisitorUtil.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/ui/ExternalIdPage.java, src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/test/java/com/salesforce/dataloader/ConfigTestBase.java, src/test/java/com/salesforce/dataloader/client/PartnerClientTest.java, src/test/java/com/salesforce/dataloader/process/BulkV1CsvProcessTest.java, src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java, src/test/java/com/salesforce/dataloader/process/NAProcessTest.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
rename config property "EXTERNAL_ID_FIELD" as "IDLOOKUP_FIELD"
=> rename config property "EXTERNAL_ID_FIELD" as "IDLOOKUP_FIELD"

src/main/java/com/salesforce/dataloader/client/CompositeRESTClient.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/ui/DataSelectionPage.java, src/main/java/com/salesforce/dataloader/ui/LoadWizard.java
[work in progress] support for update using idlookup field
=> [work in progress] support for update using idlookup field

src/main/java/com/salesforce/dataloader/action/AbstractLoadAction.java, src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java
perform client-side field truncation if using REST API for updates
=> support field truncation in REST

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/resources/labels.properties
enable/disable data compression and timeout settings with "use SOAP API" as they are applicable only when SOAP API is used.
=> enable/disable data compression and timeout settings with "use SOAP API"

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/resources/labels.properties
- refactor the code to create setting labels
=> code refactor settings dialog

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/resources/labels.properties
Use Link instead of Tooltip to if help for a setting is documented
=> Use Link instead of Tooltip to if help for a setting is documented

src/main/java/com/salesforce/dataloader/ui/LoaderWindow.java
fix bug where data loader menu failed to render intermittently
=> fix bug where data loader menu failed to render intermittently

src/main/java/com/salesforce/dataloader/action/AbstractAction.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkApiVisitorUtil.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkV1QueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/client/ClientBase.java, src/main/java/com/salesforce/dataloader/client/CompositeRESTClient.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/exception/ExtractExceptionOnServer.java, src/main/java/com/salesforce/dataloader/exception/LoadExceptionOnServer.java
Centralize "retry operation" if server side failure occurs.
=> Centralize "retry operation" so that it is used for all operations

src/main/java/com/salesforce/dataloader/client/PartnerClient.java
cache parent sobject describes if there is no filtering by mapped fields
=> cache parent sobject describes

src/main/java/com/salesforce/dataloader/ui/DataSelectionPage.java
fix regression in showing idlookup field selection page for upsert
=> fix regression in showing idlookup field selection page for upsert

src/main/java/com/salesforce/dataloader/action/visitor/BulkApiVisitorUtil.java
do not set request content type to ZIP_CSV for Bulk v2
=> do not set request content type to ZIP_CSV for Bulk v2

src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/resources/labels.properties
show max import and export batch sizes in Settings dialog
=> show max import and export batch sizes in Settings dialog

src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/resources/labels.properties, src/test/java/com/salesforce/dataloader/process/DatabaseProcessTest.java
- show min and max export batch size in Settings dialog
- enable change of export batch size without having to logout and login again
=> export batch size setting improvements

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/resources/labels.properties
help link for serial mode and binary content settings
=> help link for serial mode and binary content settings

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/resources/labels.properties
tooltip for "insert null values" setting
=> tooltip for "insert null values" setting

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/resources/labels.properties
minor cosmetic changes to Settings dialog
=> minor cosmetic changes to Settings dialog

src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java, src/test/resources/testfiles/data/updateAccountWithExternalIdCsvMap.sdl, src/test/resources/testfiles/data/updateAccountWithExternalIdCsvTemplate.csv
test for update operation using external id
=> test for update operation using external id

src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java
=> fix a couple of test failures

src/main/java/com/salesforce/dataloader/controller/Controller.java
Fix intermittent NPE in the code for using REST API.
=> Fix intermittent NPE

src/main/resources/win/util/util.bat
Remove the assumption that Desktop folder is always a subfolder of $HOME folder.
=> fix for issue #1182

src/main/java/com/salesforce/dataloader/action/DeleteAction.java, src/main/java/com/salesforce/dataloader/action/visitor/RESTDeleteVisitor.java, src/main/java/com/salesforce/dataloader/client/CompositeRESTClient.java, src/main/java/com/salesforce/dataloader/client/HttpClientTransport.java, src/main/java/com/salesforce/dataloader/client/HttpTransportInterface.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/ui/DataSelectionPage.java, src/main/java/com/salesforce/dataloader/ui/ExternalIdPage.java, src/main/java/com/salesforce/dataloader/ui/LoadWizard.java, src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/java/com/salesforce/dataloader/ui/MappingPage.java
work-in-progress to support deletion using an idLookup field (e.g. an external id field) when sObject Collections REST API supports it.
=> work-in-progress to support deletion using an idLookup field

pom.xml
=> DL version upgrade to v62.0.0

src/main/java/com/salesforce/dataloader/action/visitor/BulkV2Connection.java
W-16422132 - Query All does not work if Bulk V2 API is selected.
=> fix for W-16422132

src/test/java/com/salesforce/dataloader/process/CsvExtractAllProcessTest.java, src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java
include Bulk v2 in extractall tests
=> include Bulk v2 in extractall tests

src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java
Fix for NPE - use System.err.println() instead of logger.error() because logger is not initiatlized.
=> fix for issue #1208

src/main/java/com/salesforce/dataloader/action/visitor/BulkApiVisitorUtil.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java
fix the calculation of processed records for Bulk v2 upload operations
=> fix the calculation of processed records for Bulk v2 upload operations

src/main/java/com/salesforce/dataloader/action/AbstractAction.java, src/main/java/com/salesforce/dataloader/action/visitor/AbstractQueryVisitor.java, src/main/java/com/salesforce/dataloader/dyna/SforceDynaBean.java, src/main/java/com/salesforce/dataloader/mapping/LoadMapper.java, src/main/java/com/salesforce/dataloader/mapping/SOQLMapper.java, src/main/java/com/salesforce/dataloader/ui/CSVViewerDialog.java, src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/java/com/salesforce/dataloader/ui/MappingPage.java
Perf optimization as ArrayList has faster retrieval than and same insertion as LinkedList for the operations performed by data loader. Also, ArrayList has lower memory footprint than LinkedList.
=> replace LinkedList use with ArrayList

src/main/java/com/salesforce/dataloader/action/visitor/rest/RESTConnection.java, src/main/java/com/salesforce/dataloader/client/BulkV1Client.java, src/main/java/com/salesforce/dataloader/client/ClientBase.java, src/main/java/com/salesforce/dataloader/client/CompositeRESTClient.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/client/RESTClient.java
refactoring and subclassing for clarity
=> refactoring and subclassing for clarity

src/main/java/com/salesforce/dataloader/dao/DAORowCache.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileReader.java, src/main/java/com/salesforce/dataloader/dao/database/DatabaseReader.java, src/main/java/com/salesforce/dataloader/ui/DataSelectionDialog.java
avoid reading entire csv file or db entries to be uploaded multiple times by caching  it.
=> perf optimization - cache data from upload csv or db

pom.xml
DL version change from 62.0.0 to 62.0.1
=> DL version change from 62.0.0 to 62.0.1

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/resources/labels.properties
show how api settings affect undelete and hard delete operations
=> show how api settings affect undelete and hard delete operations

src/main/java/com/salesforce/dataloader/mapping/LoadMapper.java, src/main/java/com/salesforce/dataloader/mapping/Mapper.java
Compose content of a sobject field from multiple csv columns as requested at https://ideas.salesforce.com/s/idea/a0B8W00000GdnesUAB/apex-data-loader-enable-multiple-street-address-line-import
=> work in progress - support map multiple csv cols to a sobject field

src/main/java/com/salesforce/dataloader/mapping/Mapper.java, src/main/java/com/salesforce/dataloader/ui/MappingPage.java
- filter selection of existing mapping files by .sdl extension
- minor tweak in debugging message related to mapping
=> filter selection of existing mapping files by .sdl extension

src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/model/LoginCriteria.java, src/main/java/com/salesforce/dataloader/oauth/OAuthFlowUtil.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/ui/AuthenticationRunner.java, src/main/java/com/salesforce/dataloader/ui/LoginPage.java, src/main/java/com/salesforce/dataloader/ui/OAuthLoginControl.java, src/main/java/com/salesforce/dataloader/ui/UsernamePasswordLoginControl.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserLoginRunner.java, src/test/java/com/salesforce/dataloader/TestBase.java, src/test/java/com/salesforce/dataloader/client/PartnerClientTest.java, src/test/java/com/salesforce/dataloader/oauth/OAuthFlowUtilTests.java, src/test/java/com/salesforce/dataloader/oauth/OAuthSecretFlowUtilTests.java
- consistently use environment settings for OAuth and username/password auth
- rename variables and class names to reflect their purpose
- do not change endpoint settings during OAuth and username/password flows
=> auth code cleanup

src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/oauth/OAuthFlowUtil.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserLoginRunner.java, src/main/resources/labels.properties, src/test/java/com/salesforce/dataloader/oauth/OAuthFlowUtilTests.java, src/test/java/com/salesforce/dataloader/oauth/OAuthSecretFlowUtilTests.java
split server url setting into 2 settings for production and sandbox.
=> split server url setting into 2 settings for production and sandbox

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java, src/main/resources/labels.properties
users can enter auth domain URL without protocol
=> users can enter auth domain URL without protocol

src/main/java/com/salesforce/dataloader/dyna/SforceDynaBean.java
REST Update fails if it includes update of a lookup relationship field using an idLookup field on the parent object (e.g. external id field).
The fix is to generate JSON string for the idLookup field setting in the parent object and set it to the relationship field in the child object.
=> Fix for issue #1244

src/main/java/com/salesforce/dataloader/dyna/SforceDynaBean.java, src/test/resources/testfiles/data/updateAccountWithExternalIdCsvMap.sdl, src/test/resources/testfiles/data/updateAccountWithExternalIdCsvTemplate.csv
update lookup relationship in REST API using an idLookup field on the parent object.
=> test update of lookup relationship in REST API

src/main/java/com/salesforce/dataloader/mapping/Mapper.java
Use ReferenceEntitiesDescribeMap.getParent() for mapping purpose.
=> use ReferenceEntitiesDescribeMap.getParent() for mapping

src/main/java/com/salesforce/dataloader/client/HttpClientTransport.java
Try to use NTCredentials class in Apache httpclient even if NTLM domain is not set if running on Windows. Revert to UsernamePasswordCredentials class if that does not work.
This change is based on a discussion at https://stackoverflow.com/questions/51029822/how-to-choose-between-ntcredentials-and-usernamepasswordcredentials-in-a-generic
=> Use NTCredentials for proxy auth on windows

src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkLoadVisitor.java
fix intermittent error on Windows showing incorrect success or error records. Remove unused method - transferCSVContent().
=> fix intermittent error showing incorrect success or error records

src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkApiVisitorUtil.java
calculate Bulk v1 processed rows correctly
=> calculate Bulk v1 processed rows correctly

src/main/java/com/salesforce/dataloader/client/HttpClientTransport.java
Revert areEquivalentConfigs() method to https://github.com/forcedotcom/dataloader/commit/9185feb38b2616321b058f9fd518dcbc85572c56 to minimize the number of server connection setups.
=> optimize server connection setups

pom.xml
enable build and test on Windows using 7zip
=> enable build and test on Windows using 7zip

runtests.sh, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkV1Connection.java
code refactoring of BulkV1Connection and enable remote debugging of tests
=> code refactoring of BulkV1Connection and enable remote debugging of tests

src/main/java/com/salesforce/dataloader/config/Config.java
Fix bug that breaks browser-based OAuth
=> Fix bug that breaks browser-based OAuth

src/main/java/com/salesforce/dataloader/config/Config.java
fix bug in showing thick client UI for OAuth based authentication
=> fix bug in showing thick client UI for OAuth based authentication

src/test/java/com/salesforce/dataloader/config/ConfigTest.java
unit tests to verify OAuth config settings
=> unit tests to verify OAuth config settings

src/test/java/com/salesforce/dataloader/config/ConfigTest.java
minor changes to unit test for OAuth properties
=> minor changes to unit test for OAuth properties

src/main/java/com/salesforce/dataloader/client/HttpClientTransport.java
set client name and client_id in every server request
=> set client name and client_id in every server request

src/main/java/com/salesforce/dataloader/client/HttpClientTransport.java
set client name in every server request
=> set client name in every server request

src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkLoadVisitor.java, src/test/resources/testfiles/data/oneToManySforceFieldsMappingInCsvMap.sdl
Fix for W-16872438: Bulk API fails with Field name not found error if first column in csv is mapped to multiple fields.
=> fix for W-16872438

src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/oauth/OAuthFlowUtil.java, src/main/java/com/salesforce/dataloader/oauth/OAuthSecretFlowUtil.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserLoginRunner.java, src/test/java/com/salesforce/dataloader/oauth/OAuthFlowUtilTests.java, src/test/java/com/salesforce/dataloader/oauth/OAuthSecretFlowUtilTests.java
use constant instead of string literal for client_id header
=> use constant instead of string literal for client_id header

src/main/java/com/salesforce/dataloader/mapping/Mapper.java
fix bug in mapping multiple dao columns to single sf column
=> fix bug in mapping multiple dao columns to single sf column

src/main/java/com/salesforce/dataloader/client/HttpClientTransport.java, src/main/java/com/salesforce/dataloader/controller/Controller.java
increase reuse of HttpClient instance unless bulkv2 is enabled
=> increase reuse of HttpClient instance unless bulkv2 is enabled

src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
rename method in HttpClientTransport
=> rename method in HttpClientTransport

src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/java/com/salesforce/dataloader/ui/MappingPage.java, src/main/java/com/salesforce/dataloader/ui/mapping/MappingDragListener.java
automap csv columns to sobject fields when mapping page is shown
=> automap csv columns to sobject fields when mapping page is shown

src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkV2Connection.java, src/main/java/com/salesforce/dataloader/client/HttpClientTransport.java
reuse httpclient connection for all operations except for bulk v2
=> reuse httpclient connection for all operations except for bulk v2

src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkV2Connection.java
=> reuse HttpClient for Bulk v2

src/test/java/com/salesforce/dataloader/client/PartnerClientTest.java
rename Config as AppConfig to distinguish it from other Config classes such as ConnectionConfig
=> rename Config as AppConfig to distinguish it from other Config classes such as ConnectionConfig

src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java
use system proxy settings as default proxy host and port
=> use system proxy settings as default proxy host and port

src/main/java/com/salesforce/dataloader/util/AppUtil.java
reduce the log level of default proxy settings discovery
=> reduce the log level of default proxy settings discovery

pom.xml
update version number to 62.0.2
=> update version number

src/main/java/com/salesforce/dataloader/client/PartnerClient.java
more specific log error for login exception
=> more specific log error for login exception

src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java
binary content attachments are supported in SOAP. Enable in the code.
=> binary content attachments are supported in SOAP

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/resources/messages.properties
- message tweak regarding when to enable 'Import binary content' setting
- correctly show max import limit for bulk v2
=> cosmetic changes

src/test/resources/testfiles/conf/config.properties
change test settings to reflect changes to AppConfig code
=> change test settings to reflect changes to AppConfig code

src/main/java/com/salesforce/dataloader/config/AppConfig.java
minor AppConfig code refactoring
=> minor AppConfig code refactoring

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java
Fix bug in sandbox endpoint setting in Settings dialog
=> Fix bug in sandbox endpoint setting in Settings dialog

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/resources/labels.properties
use property names from AppConfig for label and tooltip lookup in labels.properties file.
=> use property names from AppConfig for label and tooltip lookup

src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/config/ConfigPropertyMetadata.java
register all properties in a registry
=> register all properties in a registry

src/main/java/com/salesforce/dataloader/client/HttpClientTransport.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/model/LoginCriteria.java, src/main/java/com/salesforce/dataloader/oauth/OAuthFlowUtil.java, src/main/java/com/salesforce/dataloader/oauth/OAuthSecretFlowUtil.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/ui/LoginPage.java, src/main/java/com/salesforce/dataloader/ui/OAuthLoginControl.java, src/main/java/com/salesforce/dataloader/ui/UsernamePasswordLoginControl.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserLoginRunner.java, src/test/java/com/salesforce/dataloader/TestBase.java, src/test/java/com/salesforce/dataloader/client/PartnerClientTest.java, src/test/java/com/salesforce/dataloader/config/ConfigTest.java, src/test/java/com/salesforce/dataloader/oauth/OAuthFlowUtilTests.java, src/test/java/com/salesforce/dataloader/oauth/OAuthSecretFlowUtilTests.java
improve code readability - change constant names and method names to better reflect their purpose and scope.
=> changes for better readability

src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/install/Installer.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java, src/test/java/com/salesforce/dataloader/ConfigTestBase.java, src/test/java/com/salesforce/dataloader/TestBase.java
move CLI option declarations to AppConfig.java
=> move CLI option declarations to AppConfig.java

src/main/java/com/salesforce/dataloader/util/LoggingUtil.java
initialize log4j configuration only once
=> initialize log4j configuration only once

src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
instantiate AppConfig by instantiating Controller
=> instantiate AppConfig by instantiating Controller

src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/ui/LoginPage.java, src/main/java/com/salesforce/dataloader/ui/OperationPage.java
- avoid infinite recursion in login attempts
- do not change/save properties if there are minor changes to wizard page size or position
=> minor bug fixes in login attempts and saving properties

src/main/java/com/salesforce/dataloader/ui/LoaderWindow.java
make sure that menubar is displayed after upgrade dialog is closed
=> make sure that menubar is displayed after upgrade dialog is closed

pom.xml
- use sortpom plugin - https://github.com/Ekryd/sortpom
- indent pom.xml elements consistently
=> improve pom.xml readability

pom.xml
run sort goal in compile phase to auto-cleanup.
=> include sort goal for pom.xml cleanup in compile phase

pom.xml
pom.xml changes made by sortpom plugin
=> pom.xml changes made by sortpom plugin

src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/test/java/com/salesforce/dataloader/config/ConfigTest.java, src/test/resources/testfiles/conf/config.properties
Fix for W-17247728 - sfdc.endpoint property (legacy property to specify Auth endpoint) is not correctly handled.
=> fix for W-17247728

src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkLoadVisitor.java
Speed improvement - Avoid unnecessary copy of a part of an ArrayList
=> Speed improvement - Avoid unnecessary copy of a part of an ArrayList

src/main/java/com/salesforce/dataloader/dao/AbstractDataReaderImpl.java, src/main/java/com/salesforce/dataloader/dao/DAORowCache.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileReader.java, src/main/java/com/salesforce/dataloader/dao/database/DatabaseReader.java
refactor common code in CSV and Database readers
=> refactor common code in CSV and Database readers

src/main/java/com/salesforce/dataloader/action/visitor/AbstractQueryVisitor.java, src/main/java/com/salesforce/dataloader/config/ConfigPropertyMetadata.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileWriter.java, src/main/java/com/salesforce/dataloader/dao/database/DatabaseWriter.java, src/main/java/com/salesforce/dataloader/model/Row.java, src/main/java/com/salesforce/dataloader/model/TableHeader.java, src/test/java/com/salesforce/dataloader/dao/CsvTest.java, src/test/java/com/salesforce/dataloader/dao/database/DatabaseTest.java, src/test/java/com/salesforce/dataloader/dao/database/DatabaseTestUtil.java, src/test/java/com/salesforce/dataloader/process/BulkV1CsvProcessTest.java, src/test/java/com/salesforce/dataloader/process/NAProcessTest.java
transition from Row to TableRow
=> switch from Row to TableRow

src/test/java/com/salesforce/dataloader/mapping/LoadMapperTest.java
test to validate a composite mapping such as:
source1,source2=dest1,dest2
=> test to validate composite mapping

src/main/java/com/salesforce/dataloader/action/visitor/AbstractVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/partner/PartnerQueryVisitor.java, src/main/java/com/salesforce/dataloader/config/ConfigPropertyMetadata.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileWriter.java, src/main/java/com/salesforce/dataloader/dao/database/DatabaseWriter.java, src/main/java/com/salesforce/dataloader/dyna/SforceDynaBean.java, src/main/java/com/salesforce/dataloader/model/Row.java, src/main/java/com/salesforce/dataloader/model/RowInterface.java, src/main/java/com/salesforce/dataloader/model/TableRow.java, src/test/java/com/salesforce/dataloader/dao/CsvTest.java, src/test/java/com/salesforce/dataloader/dao/database/DatabaseTestUtil.java, src/test/java/com/salesforce/dataloader/process/BulkV1CsvProcessTest.java, src/test/java/com/salesforce/dataloader/process/NAProcessTest.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
Refactor common code in DatabaseWriter and CSVFileWriter by introducing a common interface for Row and TableRow classes.
=> refactor common code in DatabaseWriter and CSVFileWriter

src/main/java/com/salesforce/dataloader/dao/database/DatabaseContext.java, src/main/java/com/salesforce/dataloader/dao/database/DatabaseReader.java, src/main/java/com/salesforce/dataloader/dao/database/DatabaseWriter.java, src/test/java/com/salesforce/dataloader/process/DatabaseProcessTest.java
refactor DatabaseReader and DatabaseWriter code to use RowInterface
=> refactor DatabaseReader and DatabaseWriter code to use RowInterface

src/main/java/com/salesforce/dataloader/dyna/SforceDynaBean.java, src/main/java/com/salesforce/dataloader/model/Row.java, src/main/java/com/salesforce/dataloader/model/RowInterface.java, src/main/java/com/salesforce/dataloader/model/TableHeader.java, src/main/java/com/salesforce/dataloader/model/TableRow.java
Switch SforceDynaBean from Row to TableRow for reducing memory footprint
=> Switch SforceDynaBean from Row to TableRow for reducing memory footprint

src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileWriter.java, src/main/resources/labels.properties
output CSV with BOM if output format is UTF-8 or UTF-16
=> output CSV with BOM if output format is UTF-8 or UTF-16

pom.xml
bump up data loader version to 63.0.0
=> bump up data loader version to 63.0.0

src/test/java/com/salesforce/dataloader/process/CsvEncodingProcessTest.java, src/test/java/com/salesforce/dataloader/process/CsvExtractAggregateQueryProcessTest.java
Tests should use Data Loader's CSVFileReader instead of wsc FileReader
=> Tests should use Data Loader's CSVFileReader instead of wsc FileReader

src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/client/HttpClientTransport.java, src/main/java/com/salesforce/dataloader/client/HttpClientTransportv1.java, src/main/java/com/salesforce/dataloader/dyna/FileByteArrayConverter.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserLoginRunner.java
code cleanup - more diligently close output streams
=> code cleanup - more diligently close output streams

src/main/java/com/salesforce/dataloader/action/AbstractAction.java, src/main/java/com/salesforce/dataloader/action/AbstractLoadAction.java, src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/partner/PartnerLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/rest/RESTLoadVisitor.java, src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/exception/BatchSizeLimitException.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/ui/DataSelectionDialog.java, src/main/java/com/salesforce/dataloader/ui/LoadPage.java
make sure not to exceed batch size of the ingest payload, to avoid failure of large bulk v2 upload operations
=> make sure not to exceed batch size of the uploads

src/main/java/com/salesforce/dataloader/action/AbstractAction.java, src/main/java/com/salesforce/dataloader/action/AbstractLoadAction.java, src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkApiVisitorUtil.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkLoadVisitor.java
Bulk v2 - create multiple jobs if csv upload exceeds job size limit
=> Bulk v2 - create multiple jobs if csv upload exceeds job size limit

src/main/java/com/salesforce/dataloader/util/AppUtil.java
=> close jarfile to avoid leaks

src/main/java/com/salesforce/dataloader/action/BulkLoadAction.java, src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkApiVisitorUtil.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkV2Connection.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkV2LoadVisitor.java
support for multiple jobs in bulk v2 to handle large CSV uploads (size > 150MB) by breaking up an upload operation in multiple jobs.
=> support for multiple jobs in bulk v2 to handle large CSV uploads

src/main/java/com/salesforce/dataloader/action/AbstractAction.java, src/main/java/com/salesforce/dataloader/action/AbstractLoadAction.java, src/main/java/com/salesforce/dataloader/action/BulkExtractAction.java, src/main/java/com/salesforce/dataloader/action/BulkLoadAction.java, src/main/java/com/salesforce/dataloader/action/DeleteAction.java, src/main/java/com/salesforce/dataloader/action/InsertAction.java, src/main/java/com/salesforce/dataloader/action/PartnerExtractAction.java, src/main/java/com/salesforce/dataloader/action/PartnerExtractAllAction.java, src/main/java/com/salesforce/dataloader/action/UndeleteAction.java, src/main/java/com/salesforce/dataloader/action/UpdateAction.java, src/main/java/com/salesforce/dataloader/action/UpsertAction.java, src/main/java/com/salesforce/dataloader/action/visitor/AbstractVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkV2LoadVisitor.java, src/main/java/com/salesforce/dataloader/util/LoadRateCalculator.java
correctly display processing information if bulk v2 has multiple jobs
=> correctly display processing information if bulk v2 has multiple jobs

src/test/java/com/salesforce/dataloader/dao/RichTextHTMLEncodingTest.java
add test for handling of a full-width space char in RTF field
=> add test for handling of a full-width space char in RTF field

src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
do memory leak detection for all process tests
=> do memory leak detection for all process tests

src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java
check if test is running slower than usual
=> check if test is running slower than usual

pom.xml
=> upgrade from junit4 to junit5

src/test/java/com/salesforce/dataloader/client/PartnerClientTest.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
parameterize memory leak detection thresholds to reduce false detections
=> parameterize memory leak detection thresholds to reduce false detections

src/test/java/com/salesforce/dataloader/client/PartnerClientTest.java
re-enable tests in PartnerClientTest
=> re-enable tests in PartnerClientTest

src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/main/java/com/salesforce/dataloader/util/ExitException.java, src/main/resources/messages.properties
improve code readability around exit code usage
=> improve code readability around exit code usage

src/main/java/com/salesforce/dataloader/util/DateOnlyCalendar.java, src/test/java/com/salesforce/dataloader/config/AppConfigEdgeTest.java, src/test/java/com/salesforce/dataloader/util/AppUtilTest.java, src/test/java/com/salesforce/dataloader/util/DateOnlyCalendarTest.java
unit tests for utility classes DateOnlyCalendar, AppConfig, and AppUtil with changes to DateOnlyCalendar to handle null AppConfig and null TimeZone.
=> unit tests for utility classes

src/test/java/com/salesforce/dataloader/util/LoggingUtilTest.java
unit tests for logging utility
=> unit tests for logging utility

src/main/java/com/salesforce/dataloader/util/OrderedProperties.java, src/test/java/com/salesforce/dataloader/util/OrderedPropertiesTest.java
unit tests for OrderedProperties class
=> unit tests for OrderedProperties class

src/main/java/com/salesforce/dataloader/action/visitor/AbstractQueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkV1Connection.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkV2Connection.java, src/main/java/com/salesforce/dataloader/action/visitor/rest/RESTConnection.java, src/main/java/com/salesforce/dataloader/client/HttpClientTransportv1.java, src/main/java/com/salesforce/dataloader/client/HttpTransportImpl.java, src/main/java/com/salesforce/dataloader/client/HttpTransportInterface.java, src/main/java/com/salesforce/dataloader/client/SimplePostFactory.java, src/main/java/com/salesforce/dataloader/client/SimplePostImpl.java, src/main/java/com/salesforce/dataloader/client/SimplePostInterface.java, src/main/java/com/salesforce/dataloader/client/TransportFactoryImpl.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/oauth/OAuthSecretFlowUtil.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/java/com/salesforce/dataloader/ui/AuthenticationRunner.java, src/main/java/com/salesforce/dataloader/ui/OAuthSecretFlow.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserLoginRunner.java, src/test/java/com/salesforce/dataloader/oauth/OAuthSecretFlowUtilTests.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
Rename:
HttpClientTransport to HttpTransportImpl
DefaultSimplePost to SimplePostImpl
SimplePost to SimplePostInterface
=> rename httpclient classes for consistency

src/test/java/com/salesforce/dataloader/dao/DAORowCacheTest.java
=> unit tests for DAORowCache

src/main/java/com/salesforce/dataloader/action/AbstractAction.java, src/main/java/com/salesforce/dataloader/action/AbstractExtractAction.java, src/main/java/com/salesforce/dataloader/action/AbstractLoadAction.java, src/main/java/com/salesforce/dataloader/action/visitor/AbstractQueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/AbstractVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/AbstractBulkQueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkV1QueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkV2LoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkV2QueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/partner/PartnerDeleteVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/partner/PartnerInsertVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/partner/PartnerLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/partner/PartnerQueryAllVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/partner/PartnerQueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/partner/PartnerUndeleteVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/partner/PartnerUpdateVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/partner/PartnerUpsertVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/rest/RESTDeleteVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/rest/RESTLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/rest/RESTUpdateVisitor.java, src/main/java/com/salesforce/dataloader/dao/AbstractDataReaderImpl.java, src/main/java/com/salesforce/dataloader/dao/DataReaderInterface.java, src/main/java/com/salesforce/dataloader/dao/DataWriterInterface.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileWriter.java, src/main/java/com/salesforce/dataloader/dao/database/DatabaseWriter.java, src/main/java/com/salesforce/dataloader/ui/DataSelectionDialog.java, src/main/java/com/salesforce/dataloader/util/DAORowUtil.java, src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java
rename DataReader and DataWriter interfaces to DataReaderInterface and DataWriterInterface for maintainability
=> rename DataReader and DataWriter interfaces for maintainability

src/main/java/com/salesforce/dataloader/action/AbstractAction.java, src/main/java/com/salesforce/dataloader/action/AbstractExtractAction.java, src/main/java/com/salesforce/dataloader/action/AbstractLoadAction.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/dao/DataAccessObjectFactory.java, src/main/java/com/salesforce/dataloader/dao/DataAccessObjectInterface.java, src/main/java/com/salesforce/dataloader/dao/DataReaderInterface.java, src/main/java/com/salesforce/dataloader/dao/DataWriterInterface.java, src/main/java/com/salesforce/dataloader/util/DAORowUtil.java
rename DataAccessObject interface to DataAccessObjectInterface for maintainability
=> rename DataAccessObject interface to DataAccessObjectInterface

src/test/java/com/salesforce/dataloader/client/transport/HttpClientTransportTest.java, src/test/java/com/salesforce/dataloader/dao/csv/CsvTest.java
move tests to folders that reflect the packages of the classes they test
=> move tests to folders that reflect the packages of the classes they test

src/main/java/com/salesforce/dataloader/model/TableHeader.java, src/main/java/com/salesforce/dataloader/model/TableRow.java, src/test/java/com/salesforce/dataloader/mapping/LoadMapperEdgeCasesTest.java
edge case unit tests for TableRow
=> edge case unit tests for TableRow

src/main/java/com/salesforce/dataloader/action/visitor/AbstractQueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkApiVisitorUtil.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkV1QueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkV2QueryVisitor.java
Based on https://ideas.salesforce.com/s/idea/a0B8W00000GdWDxUAN/data-loader-export-based-on-csv-input-file
a SOQL IN clause followed by (\{\<file name\>\}, \{\<column name\>\}) when specified will be used to construct the SOQL with IN clause based on values specified in the column \<column name\> of file \<file name\>.
=> read ids from csv file's column for IN clause of extract operation

src/main/java/com/salesforce/dataloader/action/visitor/AbstractQueryVisitor.java
=> set soql char limit to 100k

src/main/java/com/salesforce/dataloader/action/visitor/AbstractQueryVisitor.java, src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java
minor fix to the logic to handle IN clause with filename and column name
=> minor fix to the logic to handle IN clause with filename and column name

src/main/java/com/salesforce/dataloader/config/AppConfig.java
avoid race condition between setting and getting current appConfig to reduce test failures.
=> avoid race condition between setting and getting current appConfig

src/test/java/com/salesforce/dataloader/action/visitor/AbstractQueryVisitorTest.java, src/test/java/com/salesforce/dataloader/process/SOQLInClauseFromCSVTest.java
additional tests for soql in clause
=> additional tests for soql in clause

src/main/java/com/salesforce/dataloader/action/visitor/AbstractQueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/AbstractVisitor.java
include total from previous soql results in subtask calculations
=> include total from previous soql results in subtask calculations

src/test/java/com/salesforce/dataloader/TestBase.java
fix for intermittent test failures requiring test username and password
=> fix for intermittent test failures requiring test username and password

src/main/java/com/salesforce/dataloader/process/ProcessRunner.java
fix bug in generating error message for missing batch mode properties
=> fix bug in generating error message for missing batch mode properties

src/main/java/com/salesforce/dataloader/action/visitor/AbstractVisitor.java
initialize success and error counts to avoid errors in rate calculations
=> initialize success and error counts to avoid errors in rate calculations

src/main/java/com/salesforce/dataloader/security/EncryptionUtil.java, src/main/resources/win/bin/encrypt.bat
Fix for issue #1471 - EncryptionUtil depends on position of command line args, making it brittle if command line args contain config properties and options other than those pertinent to EncryptionUtil unless these config properties are processed and removed from args list before EncryptionUtil does its own processing.
=> Fix for issue #1471

src/main/java/com/salesforce/dataloader/config/AppConfig.java
reduce log level to appropriate level
=> reduce log level to appropriate level

src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/install/Installer.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
code cleanup - do not check for a newer release when installing and close inputstream handle after reading for the latest downloadable release.
=> code cleanup - do not check for a newer release when installing

src/main/java/com/salesforce/dataloader/install/Installer.java
skip installation if install artifacts exist even in installation mode.
=> skip installation if install artifacts exist even in installation mode.

src/main/java/com/salesforce/dataloader/security/EncryptionUtil.java
Use the first applicable command line option to perform encryption operation and discard others.
=> EncryptionUtil improve handling of multiple command line options

src/main/java/com/salesforce/dataloader/install/Installer.java
fix bug in installer code that prevented regular run
=> fix bug in installer code that prevented regular run

src/main/java/com/salesforce/dataloader/model/LoginCriteria.java, src/main/java/com/salesforce/dataloader/ui/UsernamePasswordLoginControl.java
fix the username/password auth bug when selecting Sandbox setting
=> fix the username/password auth bug when selecting Sandbox setting

src/test/java/com/salesforce/dataloader/model/LoginCriteriaTest.java
unit tests for LoginCriteria class
=> unit tests for LoginCriteria class

src/main/java/com/salesforce/dataloader/client/PartnerClient.java
possible infinite loop during login as reported in issue #1487
=> possible infinite loop during login as reported in issue #1487

pom.xml
update SWT version number in pom.xml
=> update SWT version number in pom.xml

runtests.sh
execute mvn clean goal at the start of test run
=> execute mvn clean goal at the start of test run

runtests.sh
=> test run script code cleanup

src/test/java/com/salesforce/dataloader/EncryptionUtil/EncryptionUtilTest.java
additional tests for encryption/decryption logic
=> additional tests for encryption/decryption logic

src/main/java/com/salesforce/dataloader/security/EncryptionUtil.java
refactor code for readability and maintenance
=> refactor code for readability and maintenance

src/main/java/com/salesforce/dataloader/process/ProcessRunner.java
refactor ProcessRunner for maintainability
=> refactor ProcessRunner for maintainability

src/main/java/com/salesforce/dataloader/client/transport/SimplePostFactory.java
modularize SimplePostFactory class
=> modularize SimplePostFactory class

src/main/java/com/salesforce/dataloader/config/AppConfig.java
Issue described in KI - https://issues.salesforce.com/issue/a02Ka00000eNY0L/
Fix is to set sfdc.oauth.environment to "Sandbox" if the sfdc.endpoint property is set to "test.salesforce.com".
=> fix for an issue when using DL in CLI mode in SB org

src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
refactor DataLoaderRunner for readability
=> refactor DataLoaderRunner for readability

src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
=> refactor DataLoaderRunner

pom.xml
bump up data loader version to 64.0.0
=> bump up data loader version to 64.0.0

pom.xml, src/test/java/com/salesforce/dataloader/process/DatabaseProcessTest.java
set sfdc.resetUrlOnLogin=true for running tests
=> set sfdc.resetUrlOnLogin=true for running tests

src/main/java/com/salesforce/dataloader/client/transport/HttpTransportImpl.java
=> fix for issue #1514

src/main/java/com/salesforce/dataloader/action/AbstractAction.java
W-18294205 - do not attempt a retry if a server or network error is encountered when performing inserts as retry may result in duplicate inserts.
=> fix for W-18294205

src/main/java/com/salesforce/dataloader/client/PartnerClient.java
changes introduced in the commit https://github.com/forcedotcom/dataloader/commit/107f7e1a863c2b7fc237847d323baf42bdd98d7b have regressed behavior for Professional Edition. The fix addresses the regression.
=> fix for W-18351403

src/main/java/com/salesforce/dataloader/client/ClientBase.java, src/main/java/com/salesforce/dataloader/client/LoginClient.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/test/java/com/salesforce/dataloader/client/PartnerClientTest.java, src/test/java/com/salesforce/dataloader/mapping/SOQLMapperTest.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
singleton PartnerClient and LoginClient per Controller instance.
=> singleton PartnerClient and LoginClient

src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/client/LoginClient.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/client/ReferenceEntitiesDescribeMap.java, src/main/java/com/salesforce/dataloader/client/SObjectMetaDataClient.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/dyna/SforceDynaBean.java, src/main/java/com/salesforce/dataloader/mapping/LoadMapper.java, src/main/java/com/salesforce/dataloader/mapping/Mapper.java, src/main/java/com/salesforce/dataloader/mapping/SOQLMapper.java, src/test/java/com/salesforce/dataloader/client/PartnerClientTest.java, src/test/java/com/salesforce/dataloader/mapping/LoadMapperTest.java, src/test/java/com/salesforce/dataloader/mapping/SOQLMapperTest.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
create a separate class for metadata
=> create a separate class for metadata

src/main/java/com/salesforce/dataloader/client/ClientBase.java, src/main/java/com/salesforce/dataloader/client/LoginClient.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/client/SObjectMetaDataClient.java
refactor - move ClientOperation to superclass
=> refactor - move ClientOperation to superclass

release/install/install.command, rundl.sh, runtests.sh, src/main/resources/mac/encrypt.sh, src/main/resources/mac/util/util.sh
zsh is the default shell on mac. Use zsh to execute the scripts.
=> use zsh to execute scripts

release/install/install.command, src/main/resources/mac/dataloader_console, src/main/resources/mac/encrypt.sh, src/main/resources/mac/util/util.sh
Make shell scripts posix compliant so that they can run in any shell including zsh and bash.
=> posix compliant scripts

updateSWT.py
better error handling, logging, and cleanup of temporary directories
=>  refactored code

src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserFlow.java
set property "sfdc.oauth.pkce.port" to the desired value.
=> ability to configure local pkce port

src/main/java/com/salesforce/dataloader/util/OAuthBrowserFlow.java, src/main/resources/labels.properties
move string literals to labels.properties
=> move string literals to labels.properties

rundl.sh
fix rundl.sh -d flag issues in zsh.
=> rundl.sh improvements

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/resources/labels.properties
ECA properties are settable in Settings dialog
=> ECA properties in Settings dialog

src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/oauth/OAuthFlowHandler.java, src/main/java/com/salesforce/dataloader/ui/AuthenticationRunner.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserFlow.java, src/main/resources/labels.properties
Make consumer secret optional for ECA + OAuth PKCE flow
=> consumer secret optional for ECA

src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/oauth/OAuthFlowHandler.java, src/main/java/com/salesforce/dataloader/ui/AuthenticationRunner.java, src/main/java/com/salesforce/dataloader/ui/OAuthLoginControl.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserDeviceLoginRunner.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserFlow.java, src/main/resources/labels.properties, src/main/resources/messages.properties
- prevent app from freezing if OAuth flows fail.
- clean up messages in console log and UI when login fails.
=> login dialog improvements

src/main/java/com/salesforce/dataloader/ui/LoginPage.java, src/main/java/com/salesforce/dataloader/ui/OAuthLoginControl.java, src/main/java/com/salesforce/dataloader/ui/UsernamePasswordLoginControl.java
- make sure long error messages are fully visible and copiable
- keyboard focus switch through tabbing in username+password auth
=> minor visual fixes in login dialog

src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/oauth/OAuthFlowHandler.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserFlow.java, src/main/resources/labels.properties
support for oauth browser flow
=> support for oauth browser flow

src/main/java/com/salesforce/dataloader/oauth/OAuthFlowHandler.java, src/main/java/com/salesforce/dataloader/ui/LoginPage.java
additional preflight checks for pkce and browser flow
=> additional preflight checks for pkce and browser flow

src/main/java/com/salesforce/dataloader/oauth/OAuthFlowHandler.java
fix overly restrictive check for pkce
=> fix overly restrictive check for pkce

src/main/java/com/salesforce/dataloader/action/AbstractAction.java, src/main/java/com/salesforce/dataloader/ui/uiActions/OperationUIAction.java, src/main/java/com/salesforce/dataloader/util/OAuthServerFlow.java
remove requirement to have session refresh token
=> remove requirement to have session refresh token

src/main/java/com/salesforce/dataloader/ui/uiActions/OperationUIAction.java
=> remove diagnostic log
