forcedotcom/dataloader

src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java
If the batch completes, but had at least one failure (too many locks, too much cpu, took longer than 10 mins to process, etc...) there will be a state message.  Data Loader assumes that if there is a state message, the batch failed. 
Code change only assumes failure if there is a state message and the state is "Failed".  Otherwise, it will process the results.  Result file success and errors are still processed as previous.
=> Added handling for completed batches with state message

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/ui/LoaderWindow.java, src/main/resources/labels.properties
The welcome screen doesn't provide any options over what is available on
the main window. In fact it provides less options as the user cannot
access Settings while the welcome screen is open.
This commit adds a new settings option for hiding the welcome screen as
well as a section in settings for GUI or Loader related settings
independent of the API.
Welcome Screen defaults to being shown
=> Add option to hide Welcome screen

src/main/java/com/salesforce/dataloader/ui/SettingsPage.java
Much more cleaned up version of #36
This time just moved the text box outside the `SFDC_INTERNAL` block since it's useful to anyone who has sandboxes and production environments and not just people internal to SFDC. This should address any concerns about there being duplicate boxes while still being convenient for users.
In order to change your login to a sandbox from production once
selecting an action required the user to cancel, go to settings, change
the endpoint, save, and finally go back into the action.
This patch provides a textbox for changing the login url straight from
the action settings page
=> Provide access to endpoint during login [Refactored]

pom.xml, src/main/java/com/salesforce/dataloader/process/ProcessConfig.java
This request undoes pull #40 , and it works as advertised (no file-not-found error).  But I think the better option might be to simply add "file://" service identifier to the current code.
After forking, I executed a 
1. git revert -m 1 a5a188f7f4b32c02f291acb9c4ad5dbb805f5d33
2. fixed-up pom.xml
3. committed to tggagne/dataloader and 
4. created the pull request.
Hopefully, these were the right steps.  That's more git surgery than I'm accustomed to.
=> undo pull request #40

src/main/java/com/salesforce/dataloader/dao/DataSource.java
For Issue #64, To use encrypted passwords (encrypt -e password) as database passwords inside database-conf.xml, all users need to do is use the classname "com.salesforce.dataloader.dao.database.DataSource" instead of "org.apache.commons.dbcp.BasicDataSource" in their DB connection bean.
An example would be:
```
<bean id="qa" class="com.salesforce.dataloader.dao.database.DataSource" destroy-method="close">
<property name="driverClassName" value="oracle.jdbc.OracleDriver"/>
<property name="url" value="jdbc:oracle:thin:username/@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=host.domain.lan)(PORT = 1521)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = CRXXXXA)))"/>
<property name="username" value="username"/>
<property name="password" …
```
=> New BasicDataSource subclass uses EncryptionUtil to decrypt database passwords

src/main/java/com/salesforce/dataloader/client/PartnerClient.java
This checkConnectionException never returns true even the retry condition is met, and retry has slept.
=> fix the retry never worked bug

src/main/java/com/salesforce/dataloader/dyna/DateConverter.java
To prevent errors with invalid dates (the 13th month or the 30th of
Febuary) we are moving our multi-format date parsers to be non-lenient.
=> Change date time parsing to be non-lenient

src/main/java/com/salesforce/dataloader/dyna/DateConverter.java, src/main/java/com/salesforce/dataloader/mapping/SOQLMapper.java, src/test/java/com/salesforce/dataloader/dyna/DateConverterTest.java
small bug in wsc where grouping by date causes a date string to become
a date object. Which introduces bugs in how timezone correction to GMT
is being applied.
=> fixed group by date on export converting from string to date object

pom.xml
Old release instructions with multiple line property parameter causes issue in release.  We need to release a new version to enable Oauth feature.
=> Improve the release instructions and bump the release number

src/main/java/com/salesforce/dataloader/model/LoginCriteria.java
This is fix a customer case, where user logged in using Oauth, but switched the user name and cancel it,  then the default host address is changed to the blitz url.
=> Fix url redirected after cancelation

src/main/java/com/salesforce/dataloader/model/Row.java
Fixing SF ticket W-3732361.   Dataloader command line exports objects in  windows command line environment, it will complain columns names not found while uploading to external DB.
=> Fix an issue when CLI will fail to find extracted columns while exporting to DB

src/main/java/com/salesforce/dataloader/mapping/LoadMapper.java
Fixing the partner API call mapping issue where fuzzy mapping will cause "name" to "company  name" mapping.
=> Fixing Mapping issue part 2

pom.xml, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java
We added new static variable during security fixes.  But in command line mode, they are initialized correctly.   And also bump the to 42.1.0 for release.
=> Initialize static variables for command line mode

src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionSOQLPage.java
Please find a small modification that sorts the fields prior to adding them to the checkbox table.
I'm not sure if there was a reason this wasn't being sorted, but as a frequent Dataloader user, this small addition would be a timesaver.
=> Sorts the fields array prior to adding data to checkbox table viewer

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionInputDialog.java
Some proxies use port numbers with greater than 4 digits. The settings dialog in Dataloader currently only accepts a maximum of 4 digits for the port number. This change increases the maximum to 5 digits and also increases the length of the text field appropriately.
=> Increase maximum number of proxy port digits in settings dialog

src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/config/Config.java
Sometimes we want to insert records, without duplicate rules errors.
we added config options for DuplicateRuleHeader.
=> added config for DuplicateRuleHeader

src/main/java/com/salesforce/dataloader/dao/database/DatabaseConfig.java
This change will allow using variables in the SQL's that are defined in database config file. The variables can be set in config.properties or as an environment variable.
=> use ApplicationContext instead of XmlBeanFactory

release/mac/dataloader.command, release/mac/install.command, release/win/dataloader.bat, release/win/install.bat, src/main/java/com/salesforce/dataloader/controller/Controller.java
Fix the following issues:
- installer does not let the admin specify an absolute path for the deployment.
- run script does not let the user specify location of the directory containing config.properties file through the option: salesforce.config.dir
=> fix minor limitations in installer and run scripts

src/main/java/com/salesforce/dataloader/ui/ExternalIdPage.java, src/main/java/com/salesforce/dataloader/ui/MappingDialog.java
This PR fixes this [idea](https://partners.salesforce.com/ideaView?id=0873A000000lIS0QAM).
The Dataloader only allowed to select fields that matched these criteria:
```java
// salesforce id can be used for upsert in addition to external id fields
if("id".equals(field.getName().toLowerCase())) {
extIdFields.add(field.getName());
}
if(field.isExternalId() && (field.isCreateable() || field.isUpdateable())) {
extIdFields.add(field.getName());
}
```
Yet, as per [the docs](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/access_for_fields.htm), this is in fact not the right way to filter them; instead `idLookup` should be checked:
> idLookup
> Can be used to specify a record in an upsert call. The Id field of each object has this property and some Name fields. There are …
=> allow to select all idLookup-Fields in upserts (esp. Name)

src/main/java/com/salesforce/dataloader/ui/OAuthFlow.java
Following warning is logged when OAuth browser window is displayed by DL:
Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7fc1a9255f10>) to be less than or equal to 30 but got a height of 32.000000.
The code change avoids the display of this warning which causes unnecessary concern for the users.
=> fix the warning message by specifying a higher value for cell width.

release/win/install.bat
Do not delete dataloader.ico from the installation directory. Deleting it results in the data loader shortcut and start menu option not showing data loader icon.
=> do not delete dataloader.ico from the installation directory

.gitignore, pom.xml
- versions-maven-plugin to do dependency and plugin version management (checks and updates). Run "mvn versions:use-latest-releases" to update dependencies to the latest version. Run "mvn versions:display-dependency-updates" to see which dependencies need an update.
- maven-enforcer-plugin to make sure that the maven version used supports the plugin and dependency versions specified in the pom.xml file.
- Added plugins to fix the warnings generated by "mvn versions:display-plugin-updates" command.
=> plugin for dependency management and related updates

src/main/java/com/salesforce/dataloader/client/PartnerClient.java
Upsert supports parent lookup through any field whose "idLookup" attribute is true. This includes all fields whose "externalId" attribute is true, salesforce id field, and name field of all custom objects. Consequently, added a check to include all fields whose "idLookup" attribute is true in the possible list of fields to use for parent lookup during upsert operation.
=> fix for issue #279 - support parent lookup during upsert using idLookup attribute of a field

pom.xml, src/main/java/com/salesforce/dataloader/client/PartnerClient.java
Fix for issue #342
- avoid using cached client connection when perfoming username/password login.
=> fix for issue #342

release/win/install.bat
Desktop shortcut link is created in %USERPROFILE%\Desktop folder, which is the case for most desktops. However, sometimes Desktop folder is configured in a different location, which results in the missing desktop shortcut link. Fix is to look up the registry to figure out the location of Desktop folder and create the link.
=> fix issue with creating desktop shortcut link

release/linux/dataloader.sh, release/mac/dataloader.app/Contents/MacOS/dataloader, release/win/dataloader.bat, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
Move complexities of setting the correct JVM options and java.lib.path env variable to the dir containing SWT native libs to Java code.
=> simplify bat and shell scripts to launch data loader

dlbuilder.sh, pom.xml, src/main/assembly/uber.xml, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
- remove unused code in DataLoaderRunner.java
- Make targetOS names consistent with SWT jar package names
- Use targetOS property to exclude specific SWT jar from the uber jar, thereby avoiding warning messages for untriggered exclusion patterns.
=> minor cleanup

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileWriter.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java
Data Loader extraction already contains double quotes around all values including formulas, thereby escaping them. No need to give users an additional choice to insert a single quote in addition to double quotes surrounding a formula value.
=> remove unnecessary checkbox to escape formula values in extractions

src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
minor tweak - if architecture is amd, use the string "x86_64" when searching for SWT jar file.
=> minor tweak to the fix for #370

src/main/java/com/salesforce/dataloader/client/ClientBase.java
Specify data loader app version instead of WSC API version in clientName. Doing so makes it easier for customers to identify which data loader patch version their users are using.
=> specify data loader app version instead of WSC API version in clientName

src/test/java/com/salesforce/dataloader/process/CsvEncodingProcessTest.java
Set file encoding using System.setProperty instead of java.lang.reflection.Field.setAccesssible() which is not supported in newer JDKs.
=> set file encoding using System.setProperty

src/main/java/com/salesforce/dataloader/config/Config.java
Avoid decryption twice if an encrypted property's value is already decrypted.
=> fix for issue #393

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/test/java/com/salesforce/dataloader/TestBase.java
- Do not instantiate Controller when calling ProcessRunner.getInstance().
- Remove old code that assumed packaging prior to JDK 11 upgrade (v45) to figure out default config directory.
- Set config overrides in Controller.initConfig().
=> code cleanup to separate CLI options from config properties

src/test/java/com/salesforce/dataloader/dyna/DateConverterTest.java, src/test/java/com/salesforce/dataloader/process/DateOnlyProcessTest.java, src/test/resources/testfiles/data/dateOnlyWithTimeZone.csv, src/test/resources/testfiles/data/dateOnlyWithTimeZoneMap.sdl
Removed unnecessary tests and unused fields. Also, fixed the issue that it failed when it ran as part of integration test suite but passed when ran in isolation.
=> cleanup of DateOnlyProcessTest

release/win/dataloader.bat, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
fix for issue #410 - skip setting IEVersion system property if already specified in the java system property "org.eclipse.swt.browser.IEVersion".
=> fix for issue #410 - skip setting IEVersion if already specified

src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
fix for issue #410 - remove explicit setting of org.eclipse.swt.browser.IEVersion java property. Instead, rely on SWT default. Users can override it with org.eclipse.swt.browser.DefaultType java system property set in JAVA_TOOL_OPTIONS environment variable.
=> fix for issue #410

release/win/bin/process.bat
- use -jar instead of -cp
- use the term "batch process bean id" in the help message and variable names instead of "process name" or something else.
=> minor cleanup of process.bat file

release/mac/install.command
Enable display of Terminal window to show data loader console output by creating a softlink to Data Loader bash script in the installation folder. Doing so enables troubleshooting "silent failure" of data loader script.
=> enable a way to show data loader console output

pom.xml
- latest spring-jdbc and spring-context
- Use lf character as the end-of-line character for bash scripts in linux and Mac.
=> minor updates

release/win/dataloader.bat
minor fix - make sure that JRE located in java_home\bin takes precedence over JRE in pre-existing path.
=> place java_home\bin in path before existing path

pom.xml
config directory is not part of zipped content.  its contents are created by jar execution if necessary.
=> config directory is created by jar execution

release/win/bin/process.bat, release/win/dataloader.bat
Added double-quote around JAVA_HOME environment variable to escape whitespace characters in JVM's absolute path.
Also, process.bat invokes dataloader.bat to  increase execution code between interactive and batch modes.
=> fix for issue #431

release/win/bin/encrypt.bat, release/win/bin/process.bat
- encrypt.bat uses DATALOADER_JAVA_HOME environment variable if set.
- process.bat accepts process bean properties as command line arguments.
=> minor encrypt.bat and process.bat fixes

src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
correctly support datefield.usegmt command line option for date-only fields. If set to true when invoking data loader, date-only field values will not be adjusted (1 day added) in case user's timezone is ahead of GMT. In other words, setting datefield.usegmt may result in added/modified date-only field value to be 1 day behind the value specified in CSV file depending on the value format and user's timezone.
=> Fix to support datefield.usegmt command line option

src/main/java/com/salesforce/dataloader/util/DateOnlyCalendar.java
set hour, minute, and second to 0 when setting Calendar object for date-only field to consistently transfer date-only value to server.
=> Fix for date-only field - set hour, minute, and second values to 0

src/main/java/com/salesforce/dataloader/util/DateOnlyCalendar.java
set millisec to 0 and set AM when setting Calendar object for date-only field to consistently transfer date-only value to server.
=> set millisec to 0 and set AM for date-only field

src/main/java/com/salesforce/dataloader/util/DateOnlyCalendar.java, src/test/java/com/salesforce/dataloader/dyna/DateConverterTest.java
fix and Additional tests for date-only field processing.
Fix - set hour, minute, second, and millisec to 0 only if datefield.usegmt is not set to True (if set to true, revert to old behavior, i.e. do not set time to 12AM in local time).
Also, do not increment day by 1. Just add the offset between GMT and local timezone if local timezone is ahead of GMT.
=> Fix and Additional tests for date-only field processing

pom.xml, src/main/java/com/salesforce/dataloader/ui/OAuthBrowserListener.java, src/main/java/com/salesforce/dataloader/ui/OAuthLoginFromBrowserFlow.java, src/main/java/com/salesforce/dataloader/ui/OAuthSecretFlow.java, src/main/java/com/salesforce/dataloader/ui/OAuthTokenFlow.java
Minor robustness and troubleshooting enhancements for OAuth flow:
- Try launching system browser using AWT Desktop before using native command.
- Additional troubleshooting info in debug mode to determine the browser engine used by SWT Browser widget.
Upgrade of Spring JDBC and Spring Context from 5.3.19 to 5.3.20.
=> OAuth flow - use java AWT for browser launch

pom.xml, src/main/resources/com/salesforce/dataloader/version.properties
Fix for Partner API packaging version causing "unknown version" issue when invoking Salesforce Bulk API by decoupling partner api jar version from  salesforce api version.
=> decouple partner api jar version from  salesforce api version

pom.xml, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/resources/com/salesforce/dataloader/version.properties
Extract API version from WSC Connector class' END_POINT property to ensure that both SOAP Partner API and REST Bulk API calls through WSC use the same API version.
=> extract API version from WSC

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionSOQLPage.java, src/main/resources/labels.properties
make sort of sobject field names optional in SoQL generation dialog as requested at https://ideas.salesforce.com/s/idea/a0B8W00000GdbLvUAJ/sort-order-after-data-loader-45
=> make sort of sobject field names optional in SoQL generation dialog

src/main/java/com/salesforce/dataloader/action/progress/SWTProgressAdapter.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionWizard.java
Fix for the issue reported at https://ideas.salesforce.com/s/idea/a0B8W00000GdikRUAR/data-loader-should-let-you-edit-your-soql-query-if-there-is-a-formatting-error
=> fix to keep "Edit SOQL" dialog open if incorrect SoQL syntax

src/main/java/com/salesforce/dataloader/ui/LoaderWizardDialog.java, src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtrFieldLabelProvider.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionSOQLPage.java, src/main/java/com/salesforce/dataloader/ui/mapping/SforceLabelProvider.java
Address part of the issue reported at https://ideas.salesforce.com/s/idea/a0B8W00000GddQ8UAJ/help-text-field-info-on-data-loader by displaying field type and length along with field name in edit SOQL step.
=> show field type and length in edit SOQL step

src/main/java/com/salesforce/dataloader/ui/DataSelectionPage.java
skip resize because BaseDialog handles it.
=> skip resize because BaseDialog handles it

release/mac/dataloader.app/Contents/MacOS/dataloader, release/win/dataloader.bat
Fix for issue #483 by removing double-quotes around env variable use in dataloader.bat.
Also, set PATH in the command shell script on mac at the same place as setting it in windows bat script.
=> fix for issue #483

src/main/java/com/salesforce/dataloader/client/BulkClient.java, src/main/java/com/salesforce/dataloader/client/BulkV2Client.java, src/main/java/com/salesforce/dataloader/client/ClientBase.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserLoginRunner.java, src/test/java/com/salesforce/dataloader/TestBase.java, src/test/resources/testfiles/conf/config.properties
Data Loader should be able to handle the staggered rollout of a Salesforce release by switching to the API version of the previous API release if the API version specified in WSC does not work.
Also made minor code refactoring in Controller.java and Config.java.
=> use previous API version if the API version in WSC fails

src/test/java/com/salesforce/dataloader/EncryptionUtil/EncryptionUtilTest.java
test to verify that encrypted password is correctly processed by EncryptedDataSource class, whose regression was fixed in PR #498
=> test to avoid regression fixed in PR #498

src/main/java/com/salesforce/dataloader/ui/OAuthFlow.java, src/main/java/com/salesforce/dataloader/ui/OAuthSecretFlow.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserLoginRunner.java
A class in util package such as OAuthBrowserLoginRunner should not depend on a class in UI package because util is used by batch mode and batch mode does not load SWT packages, on which UI package depends.
Fixed the issue by moving processSuccessfulLogin() static method from OAuthFlow class in UI package to OAuthBrowserLoginRunner class in util.
=> remove ui package dependency from OAuthBrowserLoginRunner

src/main/java/com/salesforce/dataloader/action/progress/ILoaderProgress.java, src/main/java/com/salesforce/dataloader/action/progress/NihilistProgressAdapter.java, src/main/java/com/salesforce/dataloader/action/progress/SWTProgressAdapter.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/test/java/com/salesforce/dataloader/TestBase.java, src/test/java/com/salesforce/dataloader/process/BulkCsvProcessTest.java, src/test/java/com/salesforce/dataloader/process/CsvProcessAttachmentTest.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
A recent refactoring and modularization of Config and Controller code exposed a latent bug in test code where test properties set during a test run can affect subsequent tests. The fix is to do the following:
- properties such as password, if set in config.properties, should be preserved.
- if the command line option to treat config.properties as read-only is set to true, do not save properties to config.properties. This is needed when running tests to ensure that the initial config.properties value are preserved across tests.
Refactored Process tests to create ProcessRunner after specifying that properties from config.properties are read-only.
Modified ILoaderProgress and its implementations to provider getters for status, message, and batchTotal.
=> test code cleanup and related changes

src/main/java/com/salesforce/dataloader/util/OAuthBrowserLoginRunner.java
Catch all exceptions in desktop.browse() call and try native methods to launch browser for OAuth.
=> fix for issue #514

release/win/bin/encrypt.bat, release/win/bin/process.bat
- call endlocal at end of the script.
- remove double-quotes when setting a variable with value of another variable.
=> minor cleanup of batch scripts

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java
- Fix for the issue described at https://github.com/forcedotcom/dataloader/issues/506#issuecomment-1196830697
- Avoid properties loaded through command line or process-conf from getting written in config.properties.
- Do not call saveConfig() when DAO is configured or entity is set.
=> A couple of minor fixes

release/win/bin/encrypt.bat, release/win/bin/process.bat, release/win/dataloader.bat, release/win/util/util.bat
Use consistent conventions - capitalize bat commands/keywords, invoke functions by starting with ':' character, have exit label.
Additional comments in process.bat to explain the implementation.
=> minor bat script cleanup

release/win/bin/process.bat, release/win/dataloader.bat, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java
Move command line argument check to Java code, thereby simplifying process.bat and dataloader.bat scripts.
=> simplify batch mode wrapper script - process.bat

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/java/com/salesforce/dataloader/process/ProcessConfig.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/main/java/com/salesforce/dataloader/util/DateOnlyCalendar.java, src/test/java/com/salesforce/dataloader/ConfigTestBase.java, src/test/java/com/salesforce/dataloader/dyna/DateConverterTest.java, src/test/java/com/salesforce/dataloader/process/CsvHardDeleteTest.java, src/test/java/com/salesforce/dataloader/process/DatabaseProcessTest.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
- Move all config properties to Config class (PROCESS_NAME, PROCESS_THREAD_NAME, CLI_OPTION_GMT_FOR_DATE_FIELD_VALUE)
- DataLoaderRunner and ProcessTestBase invoke the same method - ProcessRunner.runBatchMode(args, monitor)
Doing so increases test coverage.
=> configuration properties cleanup and increase test coverage

src/main/java/com/salesforce/dataloader/client/ClientBase.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/config/Config.java
- Added process.keepAccountTeam property for SOAP Partner operations per ask at https://ideas.salesforce.com/s/idea/a0B8W00000GdYyxUAF/dataloader-account-owner-change-keep-account-team-data-loader-45-and-above
- Added "salesforce.api.version" property, which can be set in config.properties to specify an API version that is different than WSC version.
=> support for "keep account team" and api version in config.properties

dlbuilder.sh, pom.xml, src/main/java/com/salesforce/dataloader/ui/LoaderWindow.java
- add data loader version string to the zip file name
- avoid NPE when the user closes data loader window by selecting "Quit SWT' from SWT menu.
=> add data loader version string to the zip file name.

pom.xml, src/main/java/com/salesforce/dataloader/client/PartnerClient.java
Issue #554 is caused by the fix for [W-10811419] Name (Auto-Number) field shows up and available for mapping in Data Loader when Self-Relationships field exist
An additional check that the field name is "id" and if so, allowing it as a reference field fixes the issue.
=> Fix for issue #554

pom.xml, src/main/java/com/salesforce/dataloader/action/progress/NihilistProgressAdapter.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
- Fix for W-11691940, caused by invocation of LogManager.getLogger() before being able to initialize logging related Java system variable.
- Fix for https://github.com/forcedotcom/dataloader/issues/53#issuecomment-1235277186 - exit with a non-zero error code if a non-recoverable error occurs during operation execution.
=> fix for W-11691940 and issue #53

release/win/install.bat
Fix for W-11828110 - Data Loader installation on Windows exits without successfully installing data loader when user chooses the default installation folder
=> fix failure to install data loader in the default folder on Windows

src/main/java/com/salesforce/dataloader/controller/Controller.java
Root-cause for the issue: LogManager.getLogger() gets called before Java system property "log4j2.configurationFile" gets set in Controller._doInitializeLog() method.
Fix is to make sure _doInitializeLog() gets called before Config.initializeStaticVariables() gets called.
=> Fix for W-11859516 - Data Loader v56 ignores log-conf.xml settings

release/mac/dataloader.app/Contents/MacOS/dataloader, release/win/bin/encrypt.bat, release/win/bin/process.bat, release/win/dataloader.bat
Fix for the issue of Unable to connect to DB using ojdbc11.jar from DataLoader, Fix is to set classpath with the directory where dataloader.bat, process.bat, and encrypt.bat are installed . Similar settings are used for the shell script (dataloader) in Mac for consistency.
=> fix for W-11906907 - Unable to connect to DB using ojdbc11.jar from DataLoader

src/main/java/com/salesforce/dataloader/dao/csv/CSVFileReader.java
The comment incorrectly stated that UTF-8 BOM is 0xEE 0xBB 0xBf. The correct hex value of UTF-8 BOM is 0xEF 0xBB 0xBF.
=> fix an incorrect comment about UTF8 BOM

src/main/java/com/salesforce/dataloader/action/visitor/BulkV2Connection.java, src/main/java/com/salesforce/dataloader/client/HttpClientTransport.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileReader.java, src/main/java/com/salesforce/dataloader/ui/Labels.java, src/main/java/com/salesforce/dataloader/ui/OAuthSecretFlow.java, src/main/java/com/salesforce/dataloader/ui/OAuthTokenFlow.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserLoginRunner.java, src/test/java/com/salesforce/dataloader/dao/CsvTest.java, src/test/java/com/salesforce/dataloader/process/CsvEncodingProcessTest.java, src/test/java/com/salesforce/dataloader/process/CsvExtractAggregateQueryProcessTest.java, src/test/resources/testfiles/data/csvtext_BOM_utf8.csv
Use BOMInputStream if character encoding is UTF-8, UTF-16BE, UTF-16LE, UTF-32BE, or UTF-32LE.
Add test for handling CSV file with BOM and UTF-8 charset and header fields in double quotes.
Use constant for UTF-8 string usage in the code.
=> generalize support for BOM (Byte Order Mark) in csv

src/main/java/com/salesforce/dataloader/ui/DataSelectionPage.java, src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/java/com/salesforce/dataloader/ui/MappingPage.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionDataSelectionPage.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionSOQLPage.java, src/main/java/com/salesforce/dataloader/ui/mapping/MappingDragListener.java, src/main/java/com/salesforce/dataloader/ui/mapping/MappingDropAdapter.java, src/main/java/com/salesforce/dataloader/ui/mapping/SforceDragListener.java, src/main/java/com/salesforce/dataloader/ui/mapping/SforceDropAdapter.java
Issue: Auto-match fields to columns action on Windows does not refresh display to show matched field names in the Field Mappings dialog
Root-cause: SWT versions used in Data Loader v55 and later do not correctly refresh the display on Windows.
Fix approach:
- Pack (resize) table columns before refreshing TableViewer.
- Redraw the Table widget in a TableViewer by invoking Table.redraw() method.
=> Fix for W-12442037 - Auto-match fields to columns action on Windows does not refresh display

src/main/java/com/salesforce/dataloader/mapping/LoadMapper.java, src/main/java/com/salesforce/dataloader/ui/MappingDialog.java
The fix is to preserve ordering of input fields while mapping them to selected Salesforce entity's fields during a load (insert, update, upsert, delete) operation.
=> fix to preserve input fields ordering while mapping them

src/main/java/com/salesforce/dataloader/mapping/LoadMapper.java
Keep current mappings of non-DAO fields, if any, when getMappingWithUnmappedColumns() is invoked.
=> keep current mappings of non-DAO fields

src/main/java/com/salesforce/dataloader/mapping/Mapper.java
Handle Salesforce field names correctly if a single field maps to multiple Salesforce fields whose names may be specified in different case (e.g. all caps or all lowercase).
=> part of the fix for issue #597

pom.xml
Specify Multi-release attribute to true in assembly plugin to avoid the warning:
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
The solution is based on answer at https://stackoverflow.com/questions/60741008/maven-assembly-plugin-multi-releasetrue
=> Fix for issue #603

pom.xml
log4j-api and log4j-core from 2.19.0 to 2.20.0
mockito-core from 5.0.0 to 5.1.1
maven-surefire-plugin from 3.0.0-M6 to 3.0.0-M9
maven-surefire-junit4 from 3.0.0-M8 to 3.0.0-M9
=> dependency updaqtes

src/main/java/com/salesforce/dataloader/action/visitor/BulkApiVisitorUtil.java
Fix is to clear attachments hashmap after each batch.
=> fix for W-11547073 - cannot process more than 1000 files using Bulk API

extractSWTJar.xml, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
Given that uber jar does not contain a SWT, specifying native SWT jar in CLASSPATH is sufficient. No need to extract native libs and set java.library.path.
=> no need to extract native libs from SWT

dlbuilder.sh, extractSWTJar.xml, pom.xml, release/util/util.bat, release/util/util.sh, src/main/assembly/uber.xml
Include linux SWT jars in Mac zip so that linux users don't have to build the repo to install dataloader.
Make sure that java incorrect version and no java found error messages are identical on linux, mac, and windows.
Avoid including target/classes folder in uber jar.
Skip building linux zip as Mac zip can be used to install on linux.
=> include linux SWT jars in mac zip

pom.xml, release/install/install.command, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/install/Installer.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java, src/main/resources/com/salesforce/dataloader/version.properties, src/main/resources/win/bin/encrypt.bat
- pom.xml changes
- Update spring-context from 5.3.23 to 5.3.26
- Use the maven.compiler.release property recognized by maven-compiler-plugin 3.8 and later to specify java version for the bytecode instead of java.compile.version property
- Update maven-surefire-plugin and surefire-junit4 plugin from 3.0.0-M9 to 3.0.0.
- specify DataLoaderRunner as the Main-Class in Manifest file of the jar.
- Changes to support DataLoaderRunner as the only entry point for install, batch mode, UI mode, and encrypt mode.
=> minor cleanup and version updates

release/install/install.command
Use $@ instead of %* to specify command line options in the shell script portion.
=> fix minor bug in install.command

src/main/java/com/salesforce/dataloader/util/AppUtil.java
minor fix to handle dangling symlinks when extracting artifacts from jar.
=> Fix to handle dangling symlinks when extracting artifacts from jar

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java
Users don't need to scroll to the bottom of the dialog to see Ok and Cancel buttons. Move these buttons outside scrollable area so that they are always visible.
=> Move Ok and Cancel buttons in Settings dialog out of scrolling area

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/java/com/salesforce/dataloader/process/IProcess.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java, src/main/java/com/salesforce/dataloader/util/DateOnlyCalendar.java, src/main/java/com/salesforce/dataloader/util/LoggingUtil.java, src/test/java/com/salesforce/dataloader/ConfigTestBase.java, src/test/java/com/salesforce/dataloader/TestBase.java, src/test/java/com/salesforce/dataloader/dyna/DateConverterTest.java, src/test/java/com/salesforce/dataloader/process/BulkCsvProcessTest.java, src/test/java/com/salesforce/dataloader/process/CsvExtractProcessTest.java, src/test/java/com/salesforce/dataloader/process/CsvProcessAttachmentTest.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
- Move CLI_OPTION_* to AppUtil because config properties primarily drive Controller behavior whereas CLI options are application-level.
- Centralize the use of Config.OPERATION value as the prefix of lastrun.properties file in batch mode.
- Tests invoke main method of DataLoaderRunner to make sure that tests cover application initialization code.
=> internal cleanup

extractSWTJar.xml, pom.xml, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
Remove dependency on ant-contrib by replacing foreach ant-contrib task with flatten="true" when copying SWT jar files.
=> remove dependency on ant-contrib

dlbuilder.sh, pom.xml
- pom.xml does not need to specify os-specific profiles and can build the zip file "make-shaded-jar" profile executed during package phase.
- dlbuilder.sh does not need options for codesigning as codesigning is an independent process.
- dlbuilder.sh does not need -n option because creation of zip is a part of package phase.
=> clean up pom.xml and builder script

pom.xml
data loader does not use WSC. Remove its dependency from POM.
=> remove unneeded dependency

runtests.sh
- no need to specify the API version number as a command line option
=> minor cleanup of runtests script

runtests.sh
the comment is out-of-date because we now use shade-plugin which produces shaded jar, not an uber jar.
=> update a comment

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/ui/DataSelectionDialog.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionDataSelectionPage.java
Issue: moving mapping file after using it once requires data loader restart to perform another operation.
Fix:
- make mappingFile property read-only
- add method, Controller.initializeOperation() and use it in the steps before mapping file is selected.
=> fix for W-12948382

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/main/java/com/salesforce/dataloader/ui/DataSelectionDialog.java, src/main/java/com/salesforce/dataloader/ui/MappingPage.java
Use previous operation's mapping file to pre-map fields in this operation. Also, do not try to do mapping if mapping file is missing.
=> part of the fix for W-12948382 - Consistently carry over mapping file info from previous operation

pom.xml, runtests.sh
Run unit and integration tests in package phase, after shaded jar is created to reduce chances of a bug such as W-13523757.
=> run unit and integration tests on shaded jar instead of compiled classes

src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/test/java/com/salesforce/dataloader/mapping/LoadMapperTest.java, src/test/java/com/salesforce/dataloader/mapping/RichTextHTMLEncoding.java
- separate out the tests
- read-only property to set the regex to identify HTML tags in rich text fields
=> tweaks to tests for handling richtext with html encoding

pom.xml, src/main/java/com/salesforce/dataloader/client/PartnerClient.java
Data Loader currently supports email and name as lookup fields if "isLookup == true" for these fields.
v53 introduced a change that supported any field for lookup if "isLookup == true" for that field - https://github.com/forcedotcom/dataloader/commit/f1be6679636d0b8acaad7052d4b7b450c6b83de7
It was restricted shortly afterwords to restrict the lookup mapping to name and email address fields of the lookup entity if "isLookup == true" for these fields: https://github.com/forcedotcom/dataloader/commit/901dbf402f74f1895b62ce850d29ea91200a68a1
The fix is to let any field whose "isLookup" attribute is true be used for lookup relationship mapping.
=> Fix for W-13609474 - support lookup mapping for any lookup field

src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java
- Do not replace a single whitespace character with non-breaking whitespace (&nbsp;)
- Replace multiple whitespace characters occurring next to each other with non-breaking whitespace (&nbsp;) characters to preserve the whitespace when displayed in a browser.
=> Fix for the issue reported in PR #715

src/main/java/com/salesforce/dataloader/dao/csv/CSVFileReader.java, src/main/resources/messages.properties
- Add info message to output the number of columns in the header and debug message to output the number of columns in each data row to help troubleshoot CSV related issues such as issue #717
- Replace depricated constructor for BOMInputStream with the recommended way of using BOMInputStream.builder() to get a BOMInputStream.
=> debug messages to help troubleshoot CSV issues

src/main/java/com/salesforce/dataloader/dao/csv/CSVFileReader.java
logging the number of columns for each row in a large CSV file if it is the same number as the number of header columns for debugging purposes is not useful and can bloat the debug log, making it harder to troubleshoot issues.
=> skip logging of debug message for for each CSV file row

src/main/java/com/salesforce/dataloader/dao/csv/CSVFileReader.java, src/main/resources/messages.properties
debug output of CSV column separator characters
=> debug output of CSV column separator characters

src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/ui/AuthenticationRunner.java, src/main/java/com/salesforce/dataloader/ui/uiActions/LogoutUIAction.java
Issue W-13771132 (Redundant/expensive checks for phone data types introduced in v58) is caused by invoking server API to get user locale from GetUserInfoResult. This fix fetches and caches GetUserInfoResult when the user logs in to address the issue.
=> cache GetUserInfoResult for the session

src/main/java/com/salesforce/dataloader/action/AbstractAction.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/dao/DataAccessObjectFactory.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVColumnVisitor.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileReader.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileWriter.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/ui/CSVChooserDialog.java, src/main/java/com/salesforce/dataloader/ui/CSVViewerDialog.java, src/main/java/com/salesforce/dataloader/ui/LoadFinishDialog.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionFinishDialog.java, src/main/resources/labels.properties, src/test/java/com/salesforce/dataloader/dao/CsvTest.java, src/test/java/com/salesforce/dataloader/process/BulkCsvProcessTest.java, src/test/java/com/salesforce/dataloader/process/CsvProcessWithOffsetTest.java, src/test/java/com/salesforce/dataloader/process/NAProcessTest.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
Fix for issue #723
- add property "loader.query.delimiter"
- enable its setting in "Advanced Settings" dialog with a text field labeled "Delimiter for query results:" that's set by default to comma character.
- delimiter for success and failure results csv files continues to be hardcoded as comma character.
=> Fix for issue #723

src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
log the server API invocation count when exiting in main() method instead of the shutdown hook because logger is null in the shutdown hook, resulting in a NPE.
=> log the server API invocation count when exiting

src/main/java/com/salesforce/dataloader/action/AbstractAction.java, src/main/java/com/salesforce/dataloader/action/AbstractExtractAction.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileReader.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileWriter.java, src/main/java/com/salesforce/dataloader/mapping/LoadMapper.java, src/main/java/com/salesforce/dataloader/mapping/Mapper.java, src/main/java/com/salesforce/dataloader/mapping/SOQLInfo.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java, src/main/java/com/salesforce/dataloader/util/ExceptionUtil.java, src/test/java/com/salesforce/dataloader/dao/CsvTest.java, src/test/java/com/salesforce/dataloader/process/BulkCsvProcessTest.java, src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java, src/test/java/com/salesforce/dataloader/process/NAProcessTest.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
- spelling correction: replace 'DELIMETER'  in constant names by 'DELIMITER'.
- use constant instead of string literal for comma and tab characters.
=> minor code cleanup

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/test/java/com/salesforce/dataloader/dyna/DateConverterTest.java
- consistent naming: replace "textSplitterValue" with "textUploadCSVDelimiterValue" for clarity.
- fix spelling: replace "delimeter" with "delimiter".
=> minor cleanup of variable/method names

src/main/java/com/salesforce/dataloader/install/Installer.java
Only copy the dataloader jar file to the installation folder. This avoids the issue reported in issue #740 .
=> Fix for issue #740

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/install/Installer.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/main/java/com/salesforce/dataloader/security/EncryptionAesUtil.java, src/main/java/com/salesforce/dataloader/ui/LoadWizard.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionFinishPage.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java, src/main/resources/labels.properties, src/main/resources/messages.properties, src/test/java/com/salesforce/dataloader/process/CsvExtractProcessTest.java
- Do not proceed further if the user enters <return> key without answering the prompt to install in a folder or create shortcuts.
- Display a completion message upon successful creation of a desktop or menu shortcut.
- Change the term "directory" as "folder" in user prompts, variable names, and comments to be consistent with its usage on Mac and Windows.
=> minor cleanup of install prompts

src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java, src/main/resources/mac/util/util.sh
W-13612705: [Data Loader v58 Regression] The rest of the field values are not updated if the field value of 1st data line in CSV file is blank when updating data via Data Loader Bulk API option
The regression was introduced in BulkLoadVisitor.java during the change made in PR #594 to optimize determining the header fields for each load batch. The fix is to revert the relevant code to the prior implementation.
=> fix for W-13612705

src/main/java/com/salesforce/dataloader/install/Installer.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/resources/messages.properties
Give the user choice to install data loader in the folder where it is unzipped. Doing so lets avoids the situation described in the comment https://github.com/forcedotcom/dataloader/issues/740#issuecomment-1664026175:
When I double click the dataloader-58.0.3 jar file in the extracted folder, a dataloader.bat file appears and when clicking that, I could access Data Loader, but there's no shortcut on the desktop or start menu where I could access Data Loader from, see screenshot below.
=> partial fix for issue #740

src/main/java/com/salesforce/dataloader/dao/DataAccessObjectFactory.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileReader.java, src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java, src/test/java/com/salesforce/dataloader/process/NAProcessTest.java, src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
Keeping one constructor to improve the readability of how calling code is setting the parameters.
=> code cleanup - one constructor for CSVFileReader

src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkV2Connection.java, src/main/java/com/salesforce/dataloader/config/Config.java
- set bulk v2 job size and job byte limits that match bulk v2 api limits
- ignore user settings for batch size for bulk v2 job.
- set external id value in the request body when creating bulk v2 job.
=> bulk v2 tweaks

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/resources/labels.properties
Users are confused by the need to check the checkbox for other delimiters and specify the delimiter values in Settings dialog. This fix is to remove the "Specify other delimiters checkbox" in Settings dialog. Specifying the delimiter values is sufficient to determine that other delimiter values are applicable.
=> fix to avoid issue #767

src/main/java/com/salesforce/dataloader/mapping/CaseInsensitiveMap.java, src/main/java/com/salesforce/dataloader/mapping/LoadMapper.java, src/main/java/com/salesforce/dataloader/mapping/Mapper.java
preserve the upload field order in upload CSV by introducing CaseInsensitiveMap as a subclass of LinkedHashMap to keep the fields in the same order as found in the upload CSV.
=> Redo PR #774 - preserve the upload field order in upload CSV

src/main/resources/samples/conf/database-conf.xml, src/test/resources/testfiles/conf/database-conf.xml
Replace Spring 1 DTD with Spring 2 DTD in database-conf.xml to prevent IDE from showing "attribute scope must be defined for type bean" errors.
=> Specify Spring 2 DTD in database-conf.xml

src/main/resources/samples/conf/process-conf.xml, src/test/resources/testfiles/conf/process-conf.xml
Replace Spring 1 DTD with Spring 2 DTD in process-conf.xml to prevent IDE from showing "attribute scope must be defined for type bean" errors.
=> Specify Spring 2 DTD in process-conf.xml

src/main/java/com/salesforce/dataloader/config/Config.java
Use Production as the default OAuth environment if none specified in config.properties.
=> Use Production as the default OAuth environment if none specified

src/main/java/com/salesforce/dataloader/ui/ForeignKeyExternalIdPage.java, src/main/java/com/salesforce/dataloader/ui/OperationPage.java
Do not show parent object's lookup field mapping page if the list of such possible mappings is empty.
=> Don't show lookup field mapping page if it is empty

src/main/java/com/salesforce/dataloader/ui/ForeignKeyExternalIdPage.java, src/main/resources/labels.properties
Message that explains why the user may want to select a lookup field to specify the related object during an upload operation.
=> specific message for relationship lookup field mapping page

src/main/java/com/salesforce/dataloader/mapping/Mapper.java, src/main/java/com/salesforce/dataloader/mapping/SOQLMapper.java
log mapping field exceptions instead of stopping during extract because the mapping file in config.properties may be configured for a different operation on a different object.
=> log mapping field exceptions instead of stopping during extract

runtests.sh
Too many test failures due to a systematic issue can result in a temporary lockout for the user. However, stopping on 1 test failure means a sporadic test failure can halt an entire test suite.
=> allow 5 test failures instead of 1 to allow for sporadic test failures

src/main/java/com/salesforce/dataloader/action/AbstractExtractAction.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/dao/DataWriter.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileWriter.java, src/main/java/com/salesforce/dataloader/dao/database/DatabaseWriter.java, src/main/java/com/salesforce/dataloader/mapping/Mapper.java, src/main/java/com/salesforce/dataloader/mapping/SOQLMapper.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionSOQLPage.java, src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
As SoQL adds more features such as Select FIELDS(), data loader cannot keep up with them with local checks. Adding option to skip local checks to support this.
=> skip local validation to support newer soql features

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/ui/BaseWizard.java, src/main/java/com/salesforce/dataloader/ui/LoadWizard.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionWizard.java, src/main/resources/labels.properties
keeping wizard page open when an operation completes can help the user tweak a few things and re-execute the operation more easily than having to start from the scratch.
=> setting to keep wizard page open when an operation finishes

src/main/java/com/salesforce/dataloader/action/AbstractExtractAction.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/mapping/SOQLMapper.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionSOQLPage.java, src/main/resources/labels.properties, src/test/java/com/salesforce/dataloader/mapping/SOQLMapperTest.java, src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java
The checkbox "Skip local validation of the query" is relabeled as "Limit results to the fields specified in the query" to more accurately reflect its behavior and intended purpose. Unchecking the checkbox enables user to specify queries that may not list sobject field names explicitly.
=> relabel "skip local verification of soql query" more correctly

src/main/java/com/salesforce/dataloader/action/AbstractExtractAction.java, src/main/java/com/salesforce/dataloader/dao/DataWriter.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileWriter.java, src/main/java/com/salesforce/dataloader/dao/database/DatabaseWriter.java
Output all sobject fields in the query result if output column names not set either through a mapping file, or through a mappings list provided in the UI (currently does not exist), or through extraction of query fields.
=> Output all sobject fields in the query result if output column names not set

src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionFinishDialog.java
Fix bug in viewing query error results if results delimiter is not ','
=> Fix bug in viewing query error results if results delimiter is not ','

src/main/java/com/salesforce/dataloader/action/AbstractAction.java, src/main/java/com/salesforce/dataloader/action/AbstractExtractAction.java, src/main/java/com/salesforce/dataloader/action/BulkExtractAction.java, src/main/java/com/salesforce/dataloader/action/PartnerExtractAction.java, src/main/java/com/salesforce/dataloader/action/PartnerExtractAllAction.java, src/main/java/com/salesforce/dataloader/action/visitor/AbstractBulkQueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/AbstractQueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/AbstractVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkV1QueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkV2QueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/PartnerQueryAllVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/PartnerQueryVisitor.java, src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java
Fix the issue that field mappings are not used when fields are not explicitly specified in a query.
=> field mappings when fields are not explicitly specified in a query

src/test/java/com/salesforce/dataloader/PartnerConnectionForTest.java, src/test/java/com/salesforce/dataloader/TestBase.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
Create a PartnerConnectionForTest instance for all test runs including for those where batch processing is used to create sobjects. This ensures full clean up of sobjects created during a test run.
=> test cleanup improvements

src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java
Fix for W-14287051 - Unable to insert/update a file preview image into a rich text field after data loader version 58.0.3 and higher.
The issue is due to the code skipping the check for HTML tag if there are characters outside a HTML tag. Fix is to do the HTML tag check even if there are no chars outside a HTML tag.
=> Fix for W-14287051

src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/ui/MappingDialog.java
UI mode enables the user to perform multiple operations on multiple objects in a single run (sequentially, but without having to rerun data loader). Using mapping file config property in the UI mode can result in unexpected results such as error thrown when performing extract operation or incorrect field mappings for an upload operation. The fix is to ignore mapping file property "process.mappingFile" in the UI mode.
=> ignore mapping file config property in the UI mode

src/main/java/com/salesforce/dataloader/ui/ForeignKeyExternalIdPage.java
lookup relationship field's attributes such as isCreateable and isUpdateable should be based on child object's lookup field, not the parent object's isLookup field.
=> Fix for a bug in setting lookup relationship field's attributes

src/main/java/com/salesforce/dataloader/client/DescribeRefObject.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/dyna/SObjectReference.java, src/main/java/com/salesforce/dataloader/dyna/SforceDynaBean.java, src/main/java/com/salesforce/dataloader/ui/ForeignKeyExternalIdPage.java
support relationship lookup using non-createable/non-modifiable parent field such as an autonumber field marked as an external id.
=> support lookup using non-createable/non-modifiable parent field

src/main/java/com/salesforce/dataloader/action/AbstractExtractAction.java, src/main/java/com/salesforce/dataloader/mapping/SOQLMapper.java
check SoQL syntax when skipping field extraction from query. It also checks for the presence of nested queries, not currently supported.
=> check SoQL syntax when skipping field extraction from query

src/main/java/com/salesforce/dataloader/mapping/SOQLInfo.java
The "nested queries are not supported" error message needs to be more specific because Data Loader does not support nested queries in SELECT clause. However, it supports nested queries in WHERE clause.
=> more specific error message for nested soql support

src/test/java/com/salesforce/dataloader/mapping/SoqlInfoTest.java, src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java
The message about unsupported nested queries has changed to be more specific to nested queries in SOQL SELECT clause. Tests that check for the message need to be updated too.
=> update tests related to unsupported nested queries

src/main/java/com/salesforce/dataloader/action/AbstractExtractAction.java, src/main/java/com/salesforce/dataloader/mapping/SOQLMapper.java
clear mapping when initializing ExtractAction to support correct display of soql results without closing the extraction wizard.
=> clear mapping when initializing ExtractAction

src/test/java/com/salesforce/dataloader/dyna/DateConverterTest.java
test for processing date in yyyyMMdd format to verify that the issue mentioned at https://ideas.salesforce.com/s/idea/a0B8W00000H5I2ZUAV/data-loader-sfdctimezone
=> test for processing date in yyyyMMdd format

src/main/java/com/salesforce/dataloader/client/PartnerClient.java
replace object label with object name if it starts with "__MISSING LABEL__" prefix.
=> use object name as the label if label is missing

src/test/java/com/salesforce/dataloader/dao/database/DatabaseTest.java
Fix the warning:
Unlikely argument type for equals(): DatabaseTestUtil.DateType seems to be unrelated to String
=> fix compiler warning

pom.xml
Per the issue reported at https://stackoverflow.com/questions/53918867/pluginmanagement-interferes-with-shade-plugin, <pluginManagement> tags prevent maven-shade-plugin from executing, which in turn prevents creation of shaded jar. The fix is to remove <pluginManagement> tag.
=> fix for maven-shade-plugin not executing

src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/resources/labels.properties
Data Loader v57 and earlier did not format phone fields for users in U.S. or Canada locale, resulting in the customer requests to do so such as https://ideas.salesforce.com/s/idea/a0B8W00000GdYUYUA3/phone-number-format-incorrect
v58 had the code change (https://github.com/forcedotcom/dataloader/commit/581ca6f626dc6d9eb83afad3b8d8b08076f709c4) for formatting phone fields. However, it can result in failure to upload if a validation rule such as "!REGEX(Phone,"^(\\d{10}?)?$")" is set for the phone field.
The fix is to introduce a property, sfdc.formatPhoneFields, set to false by default, which is used by data loader code to skip formatting if set to false.
=> sfdc.formatPhoneFields property to enable/disable formatting of phone field values

src/main/java/com/salesforce/dataloader/ui/LoaderWindow.java
Menubar does not get displayed if upgrade dialog pops up. The fix is to explicitly call parent's addMenuBar() method.
=> Fix for menubar not showing up when upgrade dialog pops up

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionSOQLPage.java, src/main/resources/labels.properties
User sets the property "loader.query.limitOutputToQueryFields" in Settings dialog instead of extraction wizard steps.
=> "loader.query.limitOutputToQueryFields" in Settings dialog

src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java
Fix for W-14650178 - Data Loader version 59 doesn't decode HTML entity in CSV file, resulting in double-encoding of HTML-escaped characters in a string uploaded into a Rich Text field. For example, if a string to be uploaded is "<p>ABCDE あいうえお &amp; &quot; &#127752;</p>"
Data Loader preserves all special characters such as <, >, &, which results in the following uploaded string: 
ABCDE あいうえお &amp; &quot; &#127752;
However, customers want to see the following in Rich Text field: 
ABCDE あいうえお & " 🌈
=> Fix for W-14650178

src/test/java/com/salesforce/dataloader/dao/RichTextHTMLEncodingTest.java
Test to verify that the code handles the mix of whitespace character, HTML encoded characters, and unencoded characters in the same string correctly.
=> test to avoid regression in the fix for W-14650178

src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/test/java/com/salesforce/dataloader/dao/RichTextHTMLEncodingTest.java
Convert '\n', '\r', and '\r\n' characters to <br/> tag before uploading into a RichText field. This is to preserve the newline character on the server side.
=> process unescaped newline characters as RichText field values

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/dyna/FileByteArrayConverter.java
Notes and attachments may contain text content that has whitespaces, newlines, and other non-HTML encoded characters that should be HTML encoded by Data Loader to preserve text formatting on the server.
=> Preserve whitespace and other non-HTML encoded characters in notes

README.md
Avoid reference to obsolete JRE and JDK versions in README.md by referring to the places that specify correct JRE and JDK versions.
=> refer to the places that specify JRE and JDK versions in README

src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/ui/AuthenticationRunner.java, src/main/java/com/salesforce/dataloader/ui/SettingsPage.java, src/main/resources/labels.properties, src/test/java/com/salesforce/dataloader/client/PartnerClientTest.java
Make the caching of sobject and sobject field info configurable, thereby enabling refresh of sobject info as requested at https://ideas.salesforce.com/s/idea/a0B8W00000GdnjpUAB/refresh-the-data-structure-when-logged-in-data-loader
=> configurable caching of global sobject describe and sobject fields

src/main/java/com/salesforce/dataloader/ui/MappingDialog.java
Field mapping dialog - show csv column names in the same order as listed in the csv file and let the user sort them if want to.
=> keep csv column names order in field mapping dlg

src/main/java/com/salesforce/dataloader/ui/DataSelectionDialog.java
Help avoid issues such as the one reported at https://ideas.salesforce.com/s/idea/a0B8W00000Gdp7gUAB/upload-of-note-contentnote by displaying the link to ContentNote limits information if the upload operation is on ContentNote.
=> Display link to ContentNote limits info

src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/dyna/SforceDynaBean.java, src/main/java/com/salesforce/dataloader/ui/ForeignKeyExternalIdPage.java
UI support for mapping of a polymorphic relationship through parents' idlookup fields if the possible parent sobject types are 5 or less.
=> polymorphic relationship mapping thru idlookup fields

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserLoginRunner.java
"keep account team" feature is not supported in Bulk API. So, make "keep account team" checkbox and "use bulk API" checkbox mutually exclusive.
=> make "keep account team" and "use bulk API" mutually exclusive

src/main/resources/labels.properties, src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java, src/test/resources/testfiles/data/insertAccountWithMultipleBatchesCSV.csv, src/test/resources/testfiles/data/insertAccountWithMultipleBatchesCSVMap.sdl
Test to make sure that success results show correct records when following conditions are met:
- multiple batches in the load
- some rows fail local checks
- Either SOAP API is enabled or Bulk API is enabled with process.bulk.cacheDataFromDao=true
=> tweak to UI and addition of a test

src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java
- coverage for Bulk v2
- fix bug where first row value was checked twice
=> fixes to the test for insert with multiple batches

src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java
=> re-enable tests

src/main/java/com/salesforce/dataloader/config/Config.java
Data Loader rereads DAO entries for bulk upload when processing results. Switch to caching them by default to avoid issues similar to the one reported at https://github.com/forcedotcom/dataloader/issues/506
=> Cache DAO entries for bulk upload by default

src/main/java/com/salesforce/dataloader/dyna/DateTimeConverter.java, src/test/java/com/salesforce/dataloader/dyna/DateConverterTest.java
Added tests to check that date formats specified at https://developer.salesforce.com/docs/atlas.en-us.dataLoader.meta/dataLoader/supported_data_types.htm are supported.
Fixed issue with supporting formats "GMT-08:00" and "-0800".
=> fix date conversion edge cases

src/main/java/com/salesforce/dataloader/client/PartnerClient.java
Avoid unnecessary error message
"ERROR [<process bean name>] dyna.RelationshipField <init> (RelationshipField.java:97) - field name Name does not have ':' or '-' char"
=> fix for a spurious error message

src/main/java/com/salesforce/dataloader/util/AppUtil.java
Fixed the following issue:
Data Loader creates a folder with "%20%" in the folder name for configs if installation path has a whitespace character in it. For example, if the installation path is /my/dir/with a space/v60.0.0/, data loader creates a folder /my/dir/with%20a%20space/v60.0.0/ and creates configs folder within it.
=> Fix for an issue with a whitespace char in install path

src/main/java/com/salesforce/dataloader/action/visitor/AbstractQueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkV2Connection.java, src/main/java/com/salesforce/dataloader/client/ClientBase.java, src/main/java/com/salesforce/dataloader/client/HttpClientTransport.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/exception/HttpClientTransportException.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/resources/labels.properties, src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java
Query results of Rich Text Fields (RTF) include URL of images in RTF, not the content of images, which is an issue when migrating data from one org to another as reported at https://ideas.salesforce.com/s/idea/a0B8W00000GdgsjUAB/problem-with-rich-text-field-data-migration-to-another-salesforce-org
This PR contains the fix by introducing an advanced setting checkbox title "Include image content in query results of Rich Text Fields:" linked to a new property "loader.query.includeBinaryData" when set to "true" includes image content of RTF in query results.
=> Fix to include image content of RTF in query results

src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/ui/FinishPage.java, src/main/resources/labels.properties
Add a Setting "Pre-populate Results Folder input field in Finish step\n (use the folder chosen in the previous operation)" to enable/disable prepopulation of Results Folder along with the property "sfdc.ui.wizard.finishStep.prepopulateWithPreviousOpResultsFolder"
=> support for the feature request in issue #1022

pom.xml, src/test/java/com/salesforce/dataloader/process/CsvExtractProcessTest.java
added test to check for regression in W-8551311 - describeSObject for ApiEvent fails if JSON FieldType is missing in WSC.
=> added test to check for regression in W-8551311

src/main/java/com/salesforce/dataloader/ui/UsernamePasswordLoginStandardControl.java
fix layout issue on username/password login page caused by PR #1040
=> fix layout issue on username/password login page caused by PR #1040

src/main/java/com/salesforce/dataloader/ui/BaseDialog.java
- dialogs use wizard persisted position
- dialogs use their own size settings
=> dialog position and size tweaks

pom.xml
fix the warning:
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
=> fix console warning about commons-logging.jar

src/main/java/com/salesforce/dataloader/mapping/Mapper.java, src/main/java/com/salesforce/dataloader/util/OrderedProperties.java, src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java, src/test/resources/testfiles/data/extractAccountCsvMap.sdl
preserve the column name order specified in the mapping file and soql when writing query output to csv file with the order specified in the mapping file (if any) taking precedence over the  field order in soql.
=> preserve column name order specified in mapping file and soql

src/main/java/com/salesforce/dataloader/install/Installer.java
assume that the user does not want desktop, app folder (Mac) or Start menu (Windows) shortcuts if not specified in non-interactive installation.
=> do not prompt user for shortcuts in non-interactive installation mode

src/main/java/com/salesforce/dataloader/install/Installer.java
call URL.getFile() to get data loader jar file's location to be able to copy it to the destination folder.
=> fix a minor bug in installer

src/main/java/com/salesforce/dataloader/action/visitor/BulkV2Connection.java
Fix for W-15573445: Data Loader jobs fail only for Windows OS with Bulk 2.0 enabled due to incorrect Line Endings
=> Fix for bug - Data Loader Bulk v2 fail on Windows OS

src/main/java/com/salesforce/dataloader/action/visitor/RESTConnection.java, src/main/java/com/salesforce/dataloader/action/visitor/RESTLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/TestREST.java, src/main/java/com/salesforce/dataloader/client/BulkV1Client.java, src/main/java/com/salesforce/dataloader/client/ClientBase.java, src/main/java/com/salesforce/dataloader/client/HttpClientTransport.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/client/RESTClient.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/test/java/com/salesforce/dataloader/TestBase.java
Data Loader uses Partner SOAP and Bulk REST APIs. This PR sets the foundation for being able to make REST API calls, specifically Composite REST calls which are similar to Partner SOAP to be able to support newer capabilities offered by Salesforce APIs.
=> add supporting classes for using REST API

src/test/java/com/salesforce/dataloader/process/CsvExtractAggregateQueryProcessTest.java
column headers for extraction results are no longer uppercase. Fix test failure caused by non-uppercase column headers.
=> fix test failure caused by column header mismatch

src/main/java/com/salesforce/dataloader/client/PartnerClient.java
fix a bug in setFieldReferenceDescribes(Collection<String> sfFields) that prevents discovery of lookup field list for all parents of a sobject.
=> fix a bug in optimizing for batch mode and tests

src/main/java/com/salesforce/dataloader/action/OperationInfo.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/client/ClientBase.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/test/java/com/salesforce/dataloader/process/CsvExtractProcessTest.java, src/test/java/com/salesforce/dataloader/process/CsvHardDeleteTest.java, src/test/java/com/salesforce/dataloader/process/NAProcessTest.java, src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
decouple bulk v1 and bulk v2 config properties so that bulk v1 config property does not have to be set to true in order to enable bulk v2.
=> decouple bulk v1 and bulk v2 config properties

src/main/resources/mac/dataloader_console
fix for the bug in the launch script that prevents it from starting Data Loader if the installation folder path has a space character.
=> FIx for issue #1193

src/main/java/com/salesforce/dataloader/dao/csv/CSVFileWriter.java
Fix for issue #1023 - extraction column values are empty for non-aggregation functions such as format().
=> Fix for issue #1203 - extraction column values are empty for functions

src/test/java/com/salesforce/dataloader/process/CsvExtractAllProcessTest.java
fix syntax error in CsvExtractAllProcessTest introduced during commenting/uncommenting to troubleshoot an issue.
=> fix syntax error in CsvExtractAllProcessTest

src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java
Use DAO row count to allocate number of elements in DynaBean array for faster processing.
=> minor perf improvement for upload operations

src/main/java/com/salesforce/dataloader/action/visitor/AbstractVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/BulkV2Connection.java
avoid saving server-side error rows in a temporary file, thereby speeding up end-to-end processing time. Also, use Files utility to determine number of lines in error and success files, thereby avoiding row by row traversal and count of each.
=> perf improvement in bulk v2 upload

src/main/java/com/salesforce/dataloader/ui/extraction/ExtractionSOQLPage.java
Address the issue reported at https://ideas.salesforce.com/s/idea/a0B8W00000PGMNfUAP/data-loader-soql-query-reset-after-manually-editing-then-clicking-add-condition
=> fix soql query reset when selecting/unselecting a field

src/main/java/com/salesforce/dataloader/ui/MappingDialog.java, src/main/java/com/salesforce/dataloader/ui/mapping/MappingDropAdapter.java, src/main/java/com/salesforce/dataloader/ui/mapping/SforceDragListener.java
Fix the issue where cancelling drag-n-drop of a field mapping results in removal of the field from the source row.
=> Fix an issue during cancellation of drag-n-drop action for mapping

src/main/java/com/salesforce/dataloader/mapping/Mapper.java
fix to save unmapped DAO fields in mappings file without throwing NPE
=> fix to save unmapped DAO fields in mappings file without throwing NPE

src/main/java/com/salesforce/dataloader/mapping/Mapper.java
log when multiple csv columns mapping to a sobject field is ignored because sobject field is not a string or a text area field.
=> logs to help debugging mapping issues

src/main/java/com/salesforce/dataloader/mapping/Mapper.java
- initialize composite columns from DAO columns in the constructor
- do not clear info about composite columns when clearing mapping information
=> fix bug in column mapping

src/main/java/com/salesforce/dataloader/config/Config.java
Mark the following properties as read-only (do not write them to config.properties file):
- sfdc.oauth.redirecturi
- sfdc.oauth.Production.server
- sfdc.oauth.Sandbox.server
- sfdc.oauth.Production.redirecturi
- sfdc.oauth.Sandbox.redirecturi
- sfdc.oauth.clientid
- sfdc.oauth.Production.clientsecret
- sfdc.oauth.Sandbox.clientsecret
Remove OAUTH_DEFAULT_SERVER_DNS as a constant as it is a duplicate of DEFAULT_ENDPOINT_URL_SANDBOX.
=> OAuth props cleanup

pom.xml, src/main/java/com/salesforce/dataloader/client/ClientBase.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java, src/test/java/com/salesforce/dataloader/oauth/OAuthFlowUtilTests.java, src/test/java/com/salesforce/dataloader/oauth/OAuthSecretFlowUtilTests.java
- make sure that Auth endpoint uses https protocol in getters and setters.
- rename method to validate Auth endpoint to reflect its purpose.
- remove use of auth endpoint URL obtained from WSC's endpoint setting.
=> Auth code cleanup

src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/client/ReferenceEntitiesDescribeMap.java, src/main/java/com/salesforce/dataloader/dyna/ParentSObjectFormatter.java, src/main/java/com/salesforce/dataloader/dyna/SforceDynaBean.java, src/main/java/com/salesforce/dataloader/mapping/CaseInsensitiveSet.java, src/main/java/com/salesforce/dataloader/mapping/CaseInsensitiveStringMap.java, src/main/java/com/salesforce/dataloader/mapping/LoadMapper.java, src/main/java/com/salesforce/dataloader/mapping/Mapper.java, src/main/java/com/salesforce/dataloader/mapping/SOQLMapper.java, src/main/java/com/salesforce/dataloader/model/Row.java, src/test/resources/testfiles/data/updateAccountWithExternalIdCsvMap.sdl
Field names, relationship names, parent sobject names, and parent sobject idlookup field names in mappings file are case sensitive. The change is to make them case insensitive for ease-of-use in setting up mappings.
=> support case-insensitive mappings in mapping file

src/test/resources/testfiles/data/upsertFkAccountOldFormatCsvMap.sdl
verify that mappings specified in legacy mapping format are supported in case insensitive way.
=> test to verify that code supports case-insensitive mappings

src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkV2Connection.java
support territory assignment rules in bulk v2 upload ops (insert, update, upsert).
=> support territory assignment rules in bulk v2 upload ops

src/main/java/com/salesforce/dataloader/config/Config.java
save encrypted proxy password in config.properties so that user does not have to re-enter it across data loader invocations.
=> save encrypted proxy password in config.properties

src/main/java/com/salesforce/dataloader/client/HttpClientTransport.java
improve readability of code by simplifying check for null value of currentHttpClient variable.
=> code refactoring

src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/config/Config.java, src/main/java/com/salesforce/dataloader/config/LastRunProperties.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java, src/main/java/com/salesforce/dataloader/util/DAORowUtil.java, src/test/java/com/salesforce/dataloader/process/DatabaseProcessTest.java
Rename LastRun class and a couple of variables, "properties" and "lastRun" in Config class for improving readability.
=> code refactoring - class and variable renaming for clarity

src/main/java/com/salesforce/dataloader/client/HttpClientTransport.java
- rearrange methods for readability.
- do not remove existing auth and user-agent headers if they are already set.
=> minor code refactoring of HttpClientTransport

src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkV1Connection.java, src/main/java/com/salesforce/dataloader/config/Config.java
enable WSC based httpget for Bulk v1 through a read-only property "sfdc.useLegacyHttpGet" in case the new implementation of httpget has an undesirable side-effect for a customer.
=> enable WSC based httpget through a read-only property

src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
Increase the upper limit of the server invocation threshold in tests because http get also uses HttpTransportClient.connect() method, thereby increasing the number of server invocations significantly during a test run.
=> increase the upper limit of the server invocation threshold in tests

src/main/java/com/salesforce/dataloader/oauth/OAuthFlowUtil.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserLoginRunner.java, src/test/java/com/salesforce/dataloader/oauth/OAuthFlowUtilTests.java, src/test/java/com/salesforce/dataloader/oauth/OAuthSecretFlowUtilTests.java
Bulk v1 operations return error: "Destination URL not reset. The URL returned from login must be set" due to a bug introduced in PR #1247.
Fixed it by calling config.setAuthEndpoint(token.getInstanceUrl()) that was removed in PR #1247.
=> Fix for OAuth regression introduced in PR #1247

src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkV2Connection.java, src/main/java/com/salesforce/dataloader/client/DefaultSimplePost.java, src/main/java/com/salesforce/dataloader/client/HttpClientTransport.java
DefaultSimplePost duplicates the functionality provided by HttpClientTransport. Refactor the code so that DefaultSimplePost leverages HttpClientTransport methods instead of duplicating.
=> refactor of DefaultSimplePost

src/main/java/com/salesforce/dataloader/action/visitor/AbstractQueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkV1Connection.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkV2Connection.java, src/main/java/com/salesforce/dataloader/action/visitor/rest/RESTConnection.java, src/main/java/com/salesforce/dataloader/client/ClientBase.java, src/main/java/com/salesforce/dataloader/client/DefaultSimplePost.java, src/main/java/com/salesforce/dataloader/client/HttpClientTransport.java, src/main/java/com/salesforce/dataloader/client/TransportFactoryImpl.java, src/main/java/com/salesforce/dataloader/controller/Controller.java
- Use a singleton HttpClientTransport object
- Make sure that all server calls go through HttpClientTransport
- Make sure that HttpClientTransport does not close HttpClient connection if caching is enabled
- Do more extensive equality check for ConnectorConfig instances in HttpClientTransport before deciding whether to close existing HttpClient and open a new one
=> HttpClientTransport optimizations

src/main/java/com/salesforce/dataloader/mapping/LoadMapper.java, src/main/java/com/salesforce/dataloader/mapping/Mapper.java
fix regression in preserving DAO (csv or DB) column header order introduced when support for mapping multiple DAO columns to a single sobject field was introduced.
=> fix regression in preserving DAO (csv or DB) column header order

src/main/java/com/salesforce/dataloader/client/HttpClientTransport.java, src/main/java/com/salesforce/dataloader/config/Config.java
introduce read-only property, sfdc.useSysPropsForHttpClient, set to true by default, to address issues such as issue #1265 .
=> read-only property sfdc.useSysPropsForHttpClient

src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java
additional checks regarding when system proxy settings are retrieved - only when it is the first invocation of JRE in the UI mode.
=> additional checks regarding when system proxy settings are retrieved

src/main/java/com/salesforce/dataloader/config/AppConfig.java
- set the default for "process.operation" in code to "insert".
- add all properties to consider for saving to properties file before removing specific ones that should not be saved.
=> Config properties cleanup

src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java
Only save changed settings in config.properties unless salesforce.saveAllSettings=true is specified as a command line option, in which case save all settings to config.properties file.
=> only save changed setting values in config.properties

src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java, src/main/java/com/salesforce/dataloader/util/DateOnlyCalendar.java, src/test/java/com/salesforce/dataloader/dyna/DateConverterTest.java
use AppConfig getter for GMT property setting instead of AppUtil convenience wrapper.
=> use property getters consistently

src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/java/com/salesforce/dataloader/security/EncryptionUtil.java, src/test/java/com/salesforce/dataloader/EncryptionUtil/EncryptionUtilTest.java, src/test/java/com/salesforce/dataloader/PartnerConnectionForTest.java, src/test/java/com/salesforce/dataloader/TestBase.java, src/test/java/com/salesforce/dataloader/action/ExtractTest.java, src/test/java/com/salesforce/dataloader/client/HttpClientTransportTest.java, src/test/java/com/salesforce/dataloader/dao/database/DatabaseTestUtil.java, src/test/java/com/salesforce/dataloader/dyna/BooleanConverterTest.java, src/test/java/com/salesforce/dataloader/dyna/DateConverterTest.java, src/test/java/com/salesforce/dataloader/mapping/SoqlInfoTest.java, src/test/java/com/salesforce/dataloader/model/OAuthTokenTests.java, src/test/java/com/salesforce/dataloader/util/AccountRowComparator.java, src/test/java/com/salesforce/dataloader/util/AppUtilTest.java, src/test/java/com/salesforce/dataloader/util/Base64.java, src/test/java/com/salesforce/dataloader/util/DAORowUtilTest.java, src/test/java/com/salesforce/dataloader/util/LoadRateCalculatorTest.java
- all tests are subclasses of ConfigTestBase or its subclasses, thereby ensuring that AppConfig is instantiated for every test.
- AppConfig.initializeAppConfig() is called from AppConfig.getInstance(). No need to call it explicitly from outside.
- Encryption code parses command line options in a more flexible manner to support debug flag
=> code cleanup

src/main/java/com/salesforce/dataloader/config/AppConfig.java
make process.statusOutputDirectory writeable so that user preference folder for results files can be save across data loader invocations.
=> make process.statusOutputDirectory property writable

src/main/java/com/salesforce/dataloader/config/AppConfig.java
set default yoffset for wizard pages to 50 pixels instead of 0 pixels.
=> set default yoffset for wizard pages to 50 pixels

src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/config/ConfigPropertyMetadata.java, src/main/java/com/salesforce/dataloader/config/LastRunProperties.java, src/main/java/com/salesforce/dataloader/install/Installer.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java
- reduce log level for successful config and control initialization messages from INFO to DEBUG to reduce console messages to essential ones when launching
- show banner only once when launching
=> logging during start and banner display changes

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java
Do not let the user change settings if config.properties.readonly=true
=> disable ok in Settings dialog if config.properties.readonly=true

src/main/java/com/salesforce/dataloader/dyna/IntegerConverter.java, src/test/java/com/salesforce/dataloader/dyna/IntegerConverterTest.java
handle desktop locale-specific integer format in CSV data. For example, convert "10,000" in US locale to 10000 integer value when uploading CSV file data.
=> handle desktop locale-specific integer format in CSV data

src/main/java/com/salesforce/dataloader/action/AbstractLoadAction.java, src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/DAORowVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/partner/PartnerLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/rest/RESTLoadVisitor.java, src/main/java/com/salesforce/dataloader/dao/DAORowCache.java, src/main/java/com/salesforce/dataloader/dao/DataReader.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileReader.java, src/main/java/com/salesforce/dataloader/dao/database/DatabaseReader.java, src/main/java/com/salesforce/dataloader/mapping/LoadMapper.java, src/main/java/com/salesforce/dataloader/model/TableHeader.java, src/main/java/com/salesforce/dataloader/model/TableRow.java, src/main/java/com/salesforce/dataloader/util/DAORowUtil.java, src/test/java/com/salesforce/dataloader/mapping/LoadMapperTest.java
Use TableRow and TableHeader classes to represent DAO (CSV and database) rows instead of Row class for memory savings by avoiding duplication of header labels for each row.
=> reduce memory footprint of large upload jobs

src/main/java/com/salesforce/dataloader/dao/DataReader.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileReader.java, src/main/java/com/salesforce/dataloader/dao/database/DatabaseReader.java, src/main/java/com/salesforce/dataloader/ui/CSVViewerDialog.java, src/main/java/com/salesforce/dataloader/util/DAORowUtil.java, src/test/java/com/salesforce/dataloader/dao/CsvTest.java, src/test/java/com/salesforce/dataloader/process/CsvExtractProcessTest.java, src/test/java/com/salesforce/dataloader/process/CsvProcessTest.java, src/test/java/com/salesforce/dataloader/process/CsvProcessWithOffsetTest.java, src/test/java/com/salesforce/dataloader/process/NAProcessTest.java, src/test/java/com/salesforce/dataloader/process/ProcessExtractTestBase.java, src/test/java/com/salesforce/dataloader/process/ProcessTestBase.java
increase TableRow direct use - replace readRow() with readTableRow() in DataReader interface and its implementations - CsvFileReader and DatabaeReader.
=> increase TableRow direct use - replace readRow() with readTableRow()

src/main/java/com/salesforce/dataloader/action/AbstractLoadAction.java, src/main/java/com/salesforce/dataloader/action/visitor/AbstractQueryVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/AbstractVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/partner/PartnerLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/rest/RESTLoadVisitor.java, src/main/java/com/salesforce/dataloader/client/PartnerClient.java, src/main/java/com/salesforce/dataloader/dao/AbstractDataReaderImpl.java, src/main/java/com/salesforce/dataloader/dao/DataWriter.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileReader.java, src/main/java/com/salesforce/dataloader/dao/database/DatabaseReader.java, src/main/java/com/salesforce/dataloader/mapping/LoadMapper.java, src/main/java/com/salesforce/dataloader/mapping/Mapper.java, src/main/java/com/salesforce/dataloader/mapping/SOQLMapper.java, src/main/java/com/salesforce/dataloader/model/Row.java, src/test/java/com/salesforce/dataloader/mapping/LoadMapperTest.java
More extensively use TableRow by replacing Row usage. This leads to about 100% reduction in memory use for large loads.
=> reduce memory use by using TableRow instead of Row

src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/dao/csv/CSVFileWriter.java, src/main/resources/labels.properties, src/test/java/com/salesforce/dataloader/dao/CsvTest.java
config property "dataAccess.writeCharset" to output csv files in a specific charset and CSV BOM (Byte Order Mark) if charset supports CSV BOM (UTF-8, UTF-16LE, UTF-16BE, UTF-32LE, UTF_32BE).
=> config property to output csv files in a specific charset

src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/action/visitor/bulk/BulkLoadVisitor.java
reduce memory footproint for bulk and bulkv2 uploads - do not cache job rows in DAOLoadVisitor class as they are already cached in DAOReader subclasses.
=> reduce memory footproint for bulk and bulkv2 uploads

src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/test/java/com/salesforce/dataloader/dao/RichTextHTMLEncodingTest.java
- replace line break characters with `"<br/>"` if the field value does not contain any HTML formatting.
- Replace line break characters with a single half-width space character if the field value contains HTML formatting.
- Use unicode based check of characters in the field value to detect and replace consecutive whitespace chars with non-breaking space char `'&nbsp;'`.
=> RTF field value formatting improvements

src/test/java/com/salesforce/dataloader/mapping/SoqlInfoTest.java
Fix SoqlInfoTest failure caused by exception text change
=> Fix SoqlInfoTest failure caused by exception text change

src/main/java/com/salesforce/dataloader/action/visitor/DAOLoadVisitor.java, src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/dyna/SObjectReference.java, src/test/resources/testfiles/data/insertTaskWithContactAsWhoCsv.csv, src/test/resources/testfiles/data/upsertAccountCsvTemplate.csv, src/test/resources/testfiles/data/upsertAccountSmallTemplate.csv
trim leading and trailing whitespace chars in idlookup field of a relationship during uploads if sfdc.load.removeNonBreakingSpaceInIdLookupField is set to true (default is true). This is to work around server side not handling leading and trailing full-width space chars in the same way as half-width space chars.
=> trim leading and trailing whitespace chars in relationship lookup

src/main/java/com/salesforce/dataloader/action/visitor/AbstractQueryVisitor.java, src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/test/java/com/salesforce/dataloader/process/SOQLInClauseFromCSVTest.java
config property "sfdc.soql.maxlength" to override default max chars in soql on the client side.
=> config.property to specify max chars in soql on the client side.

src/main/java/com/salesforce/dataloader/mapping/LoadMapper.java, src/main/java/com/salesforce/dataloader/mapping/Mapper.java, src/test/java/com/salesforce/dataloader/mapping/LoadMapperTest.java
W-17702537 - handle csv column name containing ',' char correctly
=> Fix W-17702537 - handle csv column name containing ',' char correctly

release/install/install.command, rundl.sh, src/main/java/com/salesforce/dataloader/util/AppUtil.java, src/main/resources/win/bin/process.bat
Pass run.mode as the first command line option in the wrapper scripts. Also, use "__REMAINING_ARG__" entries in argmap to populate position-specific command line parameters in batch mode.
=> pass run.mode as the first command line option in the wrapper scripts

src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/process/DataLoaderRunner.java, src/main/java/com/salesforce/dataloader/security/EncryptionUtil.java, src/main/java/com/salesforce/dataloader/util/AppUtil.java, src/test/java/com/salesforce/dataloader/util/AppUtilTest.java
- avoid multiple calls to convert from array of command line arguments to a map of command line arguments.
- avoid conversion from command line arguments map to command line arguments array
- move convertCommandArgsArrayToArgMap() to DataLoaderRunner and rename it configureRunModeAndGetArgsMap() to better reflect its purpose.
=> code cleanup - refactor

src/main/java/com/salesforce/dataloader/client/ClientBase.java
Fix for the regression introduced in v61 regarding SOAP trace logging in CLI mode:
Trace logging for SOAP API calls is broken in v61.0.0 and later releases
=> fix for W-18207625

src/main/java/com/salesforce/dataloader/install/Installer.java, src/main/resources/mac/util/util.sh, src/main/resources/version.properties, src/main/resources/win/util/util.bat
- java version check in java code reduces code duplication in util.sh and util.bat
- invoke :CreateShortcut in util.bat directly from Installer.java, thereby avoiding wrapper functions :createStartMenuShortcut and :createDesktopShortcut and reducing native code in util.bat
=> reduce reliance on os-native scripts

src/main/java/com/salesforce/dataloader/install/Installer.java, src/main/resources/mac/util/util.sh, src/main/resources/version.properties, src/main/resources/win/util/util.bat
having java version check in java code itself does not work because older versions of JRE complains about incompatible code. Switch back to having java version check in wrapper scripts.
=> java version check in wrapper scripts

updateSWT.py
change logic to extract SWT to a temp folder and overwrite content of the local repo instead of moving existing SWT artifacts to a save folder before checking for SWT version update or performing an update.
=> tweaks to improve the script

src/main/resources/mac/util/util.sh, src/main/resources/win/util/util.bat
fix #1564 by setting --enable-native-access=ALL-UNNAMED for Java Runtime to suppress the warning.
=> fix for issue #1564

pom.xml
jface 3.37.0 causes data loader to fail with the following error:
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/swt/internal/NativeImageLoader
at org.eclipse.jface.resource.URLImageDescriptor.loadImageFromStream(URLImageDescriptor.java:152)
at org.eclipse.jface.resource.URLImageDescriptor.getImageData(URLImageDescriptor.java:137)
at org.eclipse.jface.resource.URLImageDescriptor.getImageData(URLImageDescriptor.java:109)
...
=> revert jface from 3.37.0 to 3.36.0

src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/oauth/OAuthSecretFlowUtil.java, src/main/java/com/salesforce/dataloader/ui/AuthenticationRunner.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserDeviceLoginRunner.java, src/main/java/com/salesforce/dataloader/util/OAuthBrowserFlow.java, src/main/resources/labels.properties, src/main/resources/messages.properties
Ability to specify External Client Application settings in Data Loader using following properties:
sfdc.oauth.useExternalClientApp - boolean flag
sfdc.oauth.Production.eca.clientid
sfdc.oauth.Production.eca.clientsecret
sfdc.oauth.Sandbox.eca.clientid
sfdc.oauth.Sandbox.eca.clientsecret
=> introduce support for ECA

src/main/java/com/salesforce/dataloader/config/AppConfig.java
avoid the need for a separate boolean flag to check if ECA is enabled.
Removing need to set sfdc.oauth.useExternalClientApp flag.
Set two of the following 4:
sfdc.oauth.Production.eca.clientid
sfdc.oauth.Production.eca.clientsecret
OR
sfdc.oauth.Sandbox.eca.clientid
sfdc.oauth.Sandbox.eca.clientsecret
=> simplify ECA enablement check

src/main/java/com/salesforce/dataloader/ui/AdvancedSettingsDialog.java
read-only labels in Settings dialog are showing white background, which is a jarring experience for users.
=> fix white background issue

rundl.sh, src/main/java/com/salesforce/dataloader/client/LoginClient.java, src/main/java/com/salesforce/dataloader/config/AppConfig.java, src/main/java/com/salesforce/dataloader/controller/Controller.java, src/main/java/com/salesforce/dataloader/oauth/OAuthFlowHandler.java, src/main/java/com/salesforce/dataloader/process/ProcessRunner.java, src/main/java/com/salesforce/dataloader/ui/AuthenticationRunner.java
try pkce, followed by device flow
override and try device flow first by setting sfdc.oauth.device.loginfrombrowser=true
=> try pkce, followed by device flow

pom.xml
Fix compilation error in upgrading log4j-core from 2.24.3 to 2.25.0 by switching off Graal annotation processor.
Not doing so causes the following compilation error:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.14.0:compile (default-compile) on project dataloader: Compilation failure [ERROR] 	at org.apache.logging.log4j.core.config.plugins.processor.GraalVmProcessor.getReachabilityMetadataPath(GraalVmProcessor.java:224) [ERROR] 	at org.apache.logging.log4j.core.config.plugins.processor.GraalVmProcessor.writeReachabilityMetadata(GraalVmProcessor.java:191) [ERROR] 	at org.apache.logging.log4j.core.config.plugins.processor.GraalVmProcessor.process(GraalVmProcessor.java:128) [ERROR] 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.ca …
=> handle log4j-core upgrade
